// ============================================================================
// Hieroglyph artwork for the Enter Password dialog's anti-spoofing panel.
// Original 32x32 pixel art in the spirit of painted Egyptian hieroglyphs. Each
// glyph uses two or three colors: dark ink plus one or two mineral pigments
// (faience blue-green, lapis, ochre, gold), and is meant to sit on the
// papyrus-toned picture panel.
//
// Rows use the PixelIcon format from components/icons/types.ts: each character
// is a PALETTE key and "." is transparent, so the papyrus shows through.
// Render with <PixelArt art={...} cacheKey={id} />.
//
// glyphsFor() in PasswordDialog.tsx returns indices into HIEROGLYPHS, so keep
// the order stable: reordering changes the pictures every password produces.
// ============================================================================

import type { PixelIcon } from "../components/icons/types";

export interface Hieroglyph {
  /** Stable id, also used as the PixelArt cache key. */
  id: string;
  /** Plain-English name, read out by the panel's accessible label. */
  name: string;
  art: PixelIcon;
}

export const HIEROGLYPHS: readonly Hieroglyph[] = [
  // the loop-topped cross of life, blue-green faience
  {
    id: "ankh",
    name: "ankh",
    art: {
      size: 32,
      rows: [
        "................................",
        "..............kkkk..............",
        "............kkttttkk............",
        "...........kttkkkkttk...........",
        "...........ktk....ktk...........",
        "..........kttk....kttk..........",
        "..........ktk......ktk..........",
        "..........ktk......ktk..........",
        "..........ktk......ktk..........",
        "..........ktk......ktk..........",
        "..........kttk....kttk..........",
        "..........ktttk..ktttk..........",
        "...........ktttkktttk...........",
        "............kttttttk............",
        "....kkk.....kttttttk.....kkk....",
        "....kttkkkkkttttttttkkkkkttk....",
        "....kttttttttttttttttttttttk....",
        "....kttttttttttttttttttttttk....",
        "....kttkkkkkkttttttkkkkkkttk....",
        "....kkk......kttttk......kkk....",
        ".............kttttk.............",
        ".............kttttk.............",
        "............kttttttk............",
        "............kttttttk............",
        "............kttttttk............",
        "............kttttttk............",
        "............kttttttk............",
        "...........kttttttttk...........",
        "...........kttttttttk...........",
        "...........kttttttttk...........",
        "...........kkkkkkkkkk...........",
        "................................",
      ],
    },
  },
  // the wedjat eye with its brow, teardrop and spiral
  {
    id: "eye",
    name: "eye of Horus",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "...............nnnnnn...........",
        ".........nnnnnnnnnnnnnnnnnn.....",
        ".......nnnnnnnnnnnnnnnnnnnnnnn..",
        ".....nnnnnnn............nnnnnn..",
        "...nnnnnn.......................",
        "...nnn........kkkk..............",
        "...nn.....kkkkkkkkkkkk..........",
        "........kkkkkkkkkkkkkkkk........",
        ".......kkkwwkkwkkkkwwwkkkk......",
        ".....kkkwwwwkkkkkkkwwwwkkkkkkkk.",
        ".....kkwwwwwkkkkkkkwwwkkkkkkkkk.",
        ".......kkwwwwkkkkkkwkk..........",
        ".........kkkkkkkkkkk............",
        "..........kkk....k..............",
        "..........kk.....kk.............",
        "..........kk.....kk.............",
        "..........kk......k.............",
        "..........kk......kk............",
        "..........kk......kk....kkkk....",
        "..........kk.......kk...kkkk....",
        "..........kk........kk.....k....",
        "..........kk.........kkk..kk....",
        "..........kk..........kkkkk.....",
        "..........kk....................",
        "..........k.....................",
        "..........k.....................",
        "..........k.....................",
        "................................",
        "................................",
      ],
    },
  },
  // Horus the falcon in profile, with a blue-green wing
  {
    id: "falcon",
    name: "falcon",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "....................kkk.........",
        "..................kkzzzkk.......",
        "..................kzzzzzk.......",
        ".................kzzzzzzkkk.....",
        ".................kzzzzkzkzzk....",
        ".................kzzzkzzkkzk....",
        ".................kzzzkzzk.kk....",
        "................kzzzzkzzk.k.....",
        "...............kzzzzkkzk........",
        "..............kzzzzzkzzzk.......",
        "..............kkkzzzzzzzk.......",
        ".............kkttkkkkzzzzk......",
        ".............kttttttkzzzzk......",
        "............kktttttttkzzzk......",
        "............kktttttttkzzzk......",
        "............kttttttttkzzzk......",
        "...........kktttttttkzzzk.......",
        "...........kktttttttkzzzk.......",
        "...........ktttttttkzzzk........",
        "..........kkttttttkzzzk.........",
        "..........kktttttkzzzk..........",
        ".........kzktttkkzzkkk..........",
        ".........kktttkzkkk..k..........",
        "........kzktkkkk..k..k..........",
        "........kzkkkk....k..k..........",
        ".......kzzkk......k..k..........",
        "......kzzzk.......k..k..........",
        ".....kkkkk......kkkkkkkkk.......",
        "................................",
      ],
    },
  },
  // the upright ostrich feather of Maat
  {
    id: "feather",
    name: "feather",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        ".................kkkk...........",
        "...............kkwwwwk..........",
        "..............kwwwwwwwk.........",
        ".............kwnwwwwwk..........",
        "............kwwnwwwkkk..........",
        "............kwwnwwk.............",
        "............kwwnwwk.............",
        "............kwwnwwk.............",
        "...........kwwwnwwwk............",
        "...........kwwwnwwwk............",
        "...........kwwwnwwwk............",
        "...........kwwwnwwwk............",
        "...........kwwwnwwwk............",
        "...........kwwwnwwwk............",
        "...........kwwwwnwwk............",
        "...........kwwwwnwwk............",
        "...........kwwwwnwwk............",
        "............knnnnnnk............",
        "............kwwwnwwk............",
        "............knnnnnnk............",
        "............kwwwnwwk............",
        "............kwwwnwk.............",
        ".............kwwnwk.............",
        ".............kwwnk..............",
        "..............kwnk..............",
        "..............kkk...............",
        "...............k................",
        "...............k................",
        "...............k................",
        "...............k................",
      ],
    },
  },
  // a flowering reed leaf on its stalk
  {
    id: "reed",
    name: "reed",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "...............kk...............",
        "..............keek..............",
        ".............keeek..............",
        ".............keyeek.............",
        "............keeyeek.............",
        "............keeyeeek............",
        "............keeyeeek............",
        "............keeyeeek............",
        "...........keeeyeeek............",
        "...........keeeyeeek............",
        "...........keeeyeeek............",
        "............keeyeeek............",
        "............keeyeek.............",
        "............keeyeek.............",
        "............keeyeek.............",
        "............keeyeek.............",
        "............keeyek..............",
        ".............keyek..............",
        ".............keyk...............",
        "..........kk.kkkk...............",
        "...........kk.kek...............",
        "...........kekkek...............",
        "............kkkek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kkk...............",
      ],
    },
  },
  // three rows of rippling water
  {
    id: "water",
    name: "water",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "............n......n............",
        "...nnn.....nnn....nnn.....nnn...",
        "...nnnn...nnnnn..nnnnn...nnnn...",
        "..nnnnnn.nnnnnn..nnnnnn.nnnnnn..",
        ".nnn..nnnnnn.nnnnnn.nnnnnn..nnn.",
        "nnn...nnnnn...nnnn...nnnnn...nnn",
        "nnn....nnn.....nn.....nnn....nnn",
        ".n......n..............n......n.",
        "................................",
        "....tt.....tt......tt.....tt....",
        "...tttt...tttt....tttt...tttt...",
        "..tttttt..ttttt..ttttt..tttttt..",
        ".ttttttt.ttt.tttttt.ttt.ttttttt.",
        ".ttt..ttttt..tttttt..ttttt..ttt.",
        "ttt....ttt....tttt....ttt....ttt",
        "tt......tt.....tt.....tt......tt",
        "................................",
        "............n......n............",
        "...nnn.....nnn....nnn.....nnn...",
        "...nnnn...nnnnn..nnnnn...nnnn...",
        "..nnnnnn.nnnnnn..nnnnnn.nnnnnn..",
        ".nnn..nnnnnn.nnnnnn.nnnnnn..nnn.",
        "nnn...nnnnn...nnnn...nnnnn...nnn",
        "nnn....nnn.....nn.....nnn....nnn",
        ".n......n..............n......n.",
        "................................",
        "................................",
        "................................",
        "................................",
      ],
    },
  },
  // the red disk of Ra with its golden center
  {
    id: "sun",
    name: "sun disk",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        ".............kkkkkk.............",
        "..........kkkkkkkkkkkk..........",
        "........kkkkkrrrrrrkkkkk........",
        ".......kkkrrrrrrrrrrrrkkk.......",
        "......kkkrrrrrrrrrrrrrrkkk......",
        ".....kkrrrrrrrrrrrrrrrrrrkk.....",
        "....kkkrrrrrrrrrrrrrrrrrrkkk....",
        "....kkrrrrrrrrrrrrrrrrrrrrkk....",
        "...kkrrrrrrrrrrrrrrrrrrrrrrkk...",
        "...kkrrrrrrrrrrrrrrrrrrrrrrkk...",
        "...kkrrrrrrrrrrrrrrrrrrrrrrkk...",
        "..kkrrrrrrrrrrkkkkrrrrrrrrrrkk..",
        "..kkrrrrrrrrrkvvvvkrrrrrrrrrkk..",
        "..kkrrrrrrrrrkvvvvkrrrrrrrrrkk..",
        "..kkrrrrrrrrrkvvvvkrrrrrrrrrkk..",
        "..kkrrrrrrrrrkvvvvkrrrrrrrrrkk..",
        "..kkrrrrrrrrrrkkkkrrrrrrrrrrkk..",
        "...kkrrrrrrrrrrrrrrrrrrrrrrkk...",
        "...kkrrrrrrrrrrrrrrrrrrrrrrkk...",
        "...kkrrrrrrrrrrrrrrrrrrrrrrkk...",
        "....kkrrrrrrrrrrrrrrrrrrrrkk....",
        "....kkkrrrrrrrrrrrrrrrrrrkkk....",
        ".....kkrrrrrrrrrrrrrrrrrrkk.....",
        "......kkkrrrrrrrrrrrrrrkkk......",
        ".......kkkrrrrrrrrrrrrkkk.......",
        "........kkkkkrrrrrrkkkkk........",
        "..........kkkkkkkkkkkk..........",
        ".............kkkkkk.............",
        "................................",
        "................................",
      ],
    },
  },
  // the sacred dung beetle, seen from above
  {
    id: "scarab",
    name: "scarab",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "......k.................k.......",
        ".....kk......kkkkk......kk......",
        "......k.....knnnnnk.....k.......",
        "......k....knnnnnnnk....k.......",
        "......kk...knnnnnnnk...kk.......",
        "......kkk..knnnnnnnk..kkk.......",
        ".......kkk.kkkkkkkkk.kkk........",
        ".........kkktttttttkkk..........",
        ".........ktttttttttttk..........",
        "..k.....ktttttttttttttk.....k...",
        "..kk....ktttttttttttttk....kk...",
        "...k.....ktttttktttttk.....k....",
        "...kk.....kkkttkttkkk.....kk....",
        "....kkkkkktttkkkkktttkkkkkk.....",
        "........kktttttktttttkk.........",
        "........kttttttkttttttk.........",
        "........kttttttkttttttk.........",
        ".......ktttttttktttttttk........",
        ".......ktttttttktttttttk........",
        ".......ktttttttktttttttk........",
        ".......ktttttttktttttttk........",
        ".......kkttttttkttttttkk........",
        "......kkkttttttkttttttkkk.......",
        ".....kkkkttttttkttttttkkkk......",
        ".....k...ktttttktttttk...k......",
        "....kk....kttttkttttk....kk.....",
        "....kk.....kkttkttkk.....kk.....",
        "....k........kkkkk........k.....",
        "....k.....................k.....",
        "................................",
      ],
    },
  },
  // the owl, body in profile and face turned to the viewer
  {
    id: "owl",
    name: "owl",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "..............k.........k.......",
        "..............kk.kkkk..kk.......",
        "..............kvkvvvvkkvk.......",
        ".............kvvvvvvvvvvk.......",
        "..............kvvvvvvvvvk.......",
        ".............kvkkkkvkkkkvk......",
        ".............kvkvkkvkvkkvk......",
        ".............kvkvvkvkvvkvk......",
        ".............kvvkkvvvkkvk.......",
        ".............kkvvvvkvvvvk.......",
        ".............kvkvvvkvvvk........",
        "............kvvvkkkkkkkvk.......",
        "............kkkkvvvvvvvvk.......",
        "............kzzzkkkvvvvvk.......",
        "............kzzzzzkvvvvvvk......",
        "............kzzzzzkvvvvvvk......",
        "...........kkzzzzzkvvvvvk.......",
        "...........kzzzzzzkvvvvvk.......",
        "...........kzzzzzzkvvvvvk.......",
        "...........kzzzzzkvvvvvvk.......",
        "..........kkzzzzzkvvvvvk........",
        "..........kkzzzzkvvvvvk.........",
        "..........kzzzzkkvvvvvk.........",
        "..........kzzzkvvvvvkk..........",
        ".........kkzzkvvvvkkk...........",
        "........kkzkkvvkkk..k...........",
        "........kkkvvkk..k..k...........",
        ".......kvvkkk....k..k...........",
        ".......kkk.....kkkkkkkk.........",
        "................................",
      ],
    },
  },
  // a horned viper with a humped back
  {
    id: "viper",
    name: "horned viper",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "..............kkkkk.............",
        ".............kvvvvvk............",
        "............kvvzvvzvk...........",
        "...........kvvvvvvvvvk..........",
        "...........kvzvkkvvvvk..kk..kk..",
        "...........kvvk..kvzvvk.kk..kk..",
        "..........kvvvk..kvvvvk.kk..kk..",
        "..........kvvk....kvvvk..k..kk..",
        "..........kzvk....kvvvvk.k..k...",
        "..........kvvk....kvzvvk.kkkk...",
        ".........kvvk.....kvvvvvkvvvvkk.",
        ".........kvvk......kvvvvvvvkvvk.",
        "........kvzk.......kvvzvvvvvvvk.",
        ".......kvvvk........kvvvvvvvvkk.",
        "......kvzvk..........kvvvvvvk...",
        ".kkkkzvvkk............kkkkkk....",
        "kkkkkkkk........................",
        "................................",
        "................................",
        "................................",
        "................................",
      ],
    },
  },
  // a flat hand, fingers forward, thumb raised
  {
    id: "hand",
    name: "hand",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkkkkkk.........",
        "...........kkzzzzzzzzzzk........",
        "..........kzzzzzzkkkkkkk........",
        ".........kzzzzzzk.kkkkk.........",
        ".kkkkkkkkzzzzzkkkkkkk...........",
        ".kzzzzzzzzzzzzzzzzzzzkkkkkkkk...",
        ".kzzzzzzzzzzzzzzzzzzzzzzzzzzzk..",
        ".kzzzzzzzzzzzzzzzzzzzkkkkkkkkzk.",
        ".kzzzzzzzzzzzzzzzzzzzzzzzzzzzk..",
        ".kzzzzzzzzzzzzzzzzzzzzzzzzzkk...",
        ".kzzzzzzzzzzzkkkkkkkkkkkkkk.....",
        ".kkkkkkkkkkkk...................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
      ],
    },
  },
  // a pyramid with one sunlit and one shaded face
  {
    id: "pyramid",
    name: "pyramid",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "................................",
        "...............kk...............",
        "...............kk...............",
        "..............kvkk..............",
        ".............kvvvkk.............",
        ".............kvvvkk.............",
        "............kzzzzkzk............",
        "............kvvvvkzk............",
        "...........kvvvvvkzzk...........",
        "..........kvvvvvvkzzzk..........",
        "..........kzzzzzzzkzzk..........",
        ".........kvvvvvvvvkzzzk.........",
        ".........kvvvvvvvvkzzzk.........",
        "........kvvvvvvvvvkzzzzk........",
        ".......kzzzzzzzzzzkzzzzzk.......",
        ".......kvvvvvvvvvvkzzzzzk.......",
        "......kvvvvvvvvvvvvkzzzzzk......",
        "......kvvvvvvvvvvvvkzzzzzk......",
        ".....kzzzzzzzzzzzzzkzzzzzzk.....",
        "....kvvvvvvvvvvvvvvkzzzzzzzk....",
        "....kvvvvvvvvvvvvvvkzzzzzzzk....",
        "...kvvvvvvvvvvvvvvvkzzzzzzzzk...",
        "..kzzzzzzzzzzzzzzzzzkzzzzzzzzk..",
        "..kvvvvvvvvvvvvvvvvvkzzzzzzzzk..",
        ".kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
        "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
        "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
        "................................",
      ],
    },
  },
  // a blue lotus in bloom (a nod to the product name)
  {
    id: "lotus",
    name: "lotus",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "...............k................",
        "...............k................",
        "..............ktk...............",
        "..............ktk...............",
        "...........k.ktttk.k............",
        "..........ktkktttkktk...........",
        "......k...ktkktttkktk...k.......",
        "......kk..kttktttkttk..kk.......",
        "......ktk..ktktttktk..ktk.......",
        ".......ktk.ktktttktk.ktk........",
        ".......kttkktktttktkkttk........",
        "........kttktktttktkttk.........",
        "........ktttkktttkktttk.........",
        ".........kttkktttkkttk..........",
        "..........ktkktttkktk...........",
        "...........ktktttktk............",
        "............kkkkkkk.............",
        "...........kkeeeeekk............",
        "...........keeeeeeek............",
        "............kkeeekk.............",
        "..............kkk...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kek...............",
        "..............kkk...............",
      ],
    },
  },
  // the banded djed pillar of stability
  {
    id: "djed",
    name: "djed pillar",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "......kkkkkkkkkkkkkkkkkkk.......",
        "......kvvvvvvvvvvvvvvvvvk.......",
        "......kkkkkkkkkkkkkkkkkkk.......",
        "......kvvvvvvvvvvvvvvvvvk.......",
        "......kvvvvvvvvvvvvvvvvvk.......",
        "......kkkkkkkkkkkkkkkkkkk.......",
        "......kvvvvvvvvvvvvvvvvvk.......",
        "......kkkkkkkkkkkkkkkkkkk.......",
        "......kkkkkkkkkkkkkkkkkkk.......",
        "......kvvvvvvvvvvvvvvvvvk.......",
        "......kkkkkkkkkkkkkkkkkkk.......",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "...........ktttttttk............",
        "............ktttttk.............",
        "............ktttttk.............",
        "............ktttttk.............",
        "............ktttttk.............",
        "........kkkkkkkkkkkkkkk.........",
        "........kvvvvvvvvvvvvvk.........",
        "........kkkkkkkkkkkkkkk.........",
        "................................",
      ],
    },
  },
  // a five-armed star as painted on tomb ceilings
  {
    id: "star",
    name: "star",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "...............k................",
        "...............k................",
        "...............k................",
        "..............kvk...............",
        "..............kvk...............",
        "..............kvk...............",
        ".............kvvvk..............",
        ".............kvvvk..............",
        ".............kvvvk..............",
        "............kvvvvvk.............",
        "......kkkkkkvvvvvvvkkkkkk.......",
        "...kkkvvvvvvvvvvvvvvvvvvvkkk....",
        "....kvvvvvvvvvvvvvvvvvvvvvk.....",
        ".....kvvvvvvvvvvvvvvvvvvvk......",
        "......kkvvvvvvvvvvvvvvvkk.......",
        "........kvvvvvvvvvvvvvk.........",
        ".........kvvvvvvvvvvvk..........",
        "..........kvvvvvvvvvk...........",
        ".........kvvvvvvvvvvvk..........",
        ".........kvvvvvvvvvvvk..........",
        ".........kvvvvvkvvvvvk..........",
        "........kvvvvvk.kvvvvvk.........",
        "........kvvvkk...kkvvvk.........",
        "........kvvk.......kvvk.........",
        "........kkk.........kkk.........",
        ".......kk.............kk........",
        ".......k...............k........",
        "................................",
        "................................",
        "................................",
      ],
    },
  },
  // a Nile fish with spiny fins
  {
    id: "fish",
    name: "fish",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................k...............",
        "...........k...knk..............",
        "..........knkkknnnk.kk..........",
        "..........knnnnnnnnknk..........",
        ".........kkkkkkkkkkkkk..........",
        ".k........kkkkaaaakkkk..........",
        "..k.....kkaaaaaaaaaakakk........",
        "..k...kkaaaaaaaaaaaakkaak.......",
        "..kk.kaaaaaaanaaaaaaakaaak......",
        "...kkkaaaanaaaaanaaaakakak......",
        "...knkaaaaaaaaaaaaaaakaaaak.....",
        "...knkaaaaaaaaaaaaaaakaaaak.....",
        "...kkkaaaaaanaanaanaakaaakk.....",
        "..kk.kaaaaaaaaaaaaaaakaaak......",
        "..k...kkaanaaaaaaaaakkaak.......",
        "..k.....kkaaaaaanaaakakk........",
        ".k........kkkkaaaakkkkk.........",
        "............kkkkkk...kk.........",
        ".............knk.....kk.........",
        ".............kk.................",
        ".............k..................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
      ],
    },
  },
  // a seated cat with a gold collar
  {
    id: "cat",
    name: "cat",
    art: {
      size: 32,
      rows: [
        "................................",
        "................................",
        "...............kk....kk.........",
        "...............kk...kdk.........",
        "...............kdvkkddk.........",
        "...............kddddddk.........",
        "...............kddddddk.........",
        "..............kdddddvdk.........",
        "..............kddddddddk........",
        "..............kdddddddddk.......",
        "...............kvdddddkk........",
        "...............kdddddk..........",
        "............kkkddddkk...........",
        "............kvvvvvvv............",
        "...........kdddddddk............",
        "...........kdddddddk............",
        "..........kdddddddddk...........",
        "..........kdddddddddk...........",
        ".........kdddddddkddk...........",
        ".........kdddddddkddk...........",
        "........kddddddddkddk...........",
        "........kddddddddkddk...........",
        "........kddddddddkddk...........",
        "........kddddddddkddk...........",
        ".......kddddddddddkdk...........",
        ".......kddddddddddkddk..........",
        ".......kddddddddddkddk..........",
        ".......kddddddddddkddk....k.....",
        "........kdddddddddkddk..kkkk....",
        "........kdddddddddkddkkkkkk.....",
        "........kkkkkkkkkkkkkkkk........",
        "..............kkkkk.............",
      ],
    },
  },
];

/** Pictures shown while the password field is empty: ankh, eye, sun, lotus. */
export const DEFAULT_GLYPHS: readonly number[] = [0, 1, 6, 12];

/** The "stop" icon (red disk, white X) of the Wrong Password message box. */
export const STOP_ICON: PixelIcon = {
  size: 32,
  rows: [
    "................................",
    "................................",
    ".............rrrrr..............",
    "..........rrrRRRRRrrr...........",
    "........rrRRRRRRRRRRRrr.........",
    ".......rRRRRRRRRRRRRRRRr........",
    "......rRRRRRRRRRRRRRRRRRr.......",
    ".....rRRRRRRRRRRRRRRRRRRRr......",
    "....rRRRRRRRRRRRRRRRRRRRRRr.....",
    "....rRRRRwwwRRRRRRRwwwRRRRrg....",
    "...rRRRRRwwwwRRRRRwwwwRRRRRrg...",
    "...rRRRRRwwwwwRRRwwwwwRRRRRr....",
    "...rRRRRRRwwwwwRwwwwwRRRRRRrg...",
    "..rRRRRRRRRwwwwwwwwwRRRRRRRRrg..",
    "..rRRRRRRRRRwwwwwwwRRRRRRRRRr.g.",
    "..rRRRRRRRRRRwwwwwRRRRRRRRRRrg..",
    "..rRRRRRRRRRwwwwwwwRRRRRRRRRr.g.",
    "..rRRRRRRRRwwwwwwwwwRRRRRRRRrg..",
    "...rRRRRRRwwwwwRwwwwwRRRRRRrg.g.",
    "...rRRRRRwwwwwRRRwwwwwRRRRRr.g..",
    "...rRRRRRwwwwRRRRRwwwwRRRRRrg.g.",
    "....rRRRRwwwRRRRRRRwwwRRRRrg.g..",
    "....rRRRRRRRRRRRRRRRRRRRRRr.g...",
    ".....rRRRRRRRRRRRRRRRRRRRr.g.g..",
    "......rRRRRRRRRRRRRRRRRRr.g.g...",
    ".......rRRRRRRRRRRRRRRRr.g.g....",
    "........rrRRRRRRRRRRRrr.g.g.....",
    ".........grrrRRRRRrrrg.g.g......",
    "..........g.grrrrrg.g.g.g.......",
    ".............g.g.g.g.g.g........",
    "..............g.g.g.g...........",
    "................................",
  ],
};
