// ============================================================================
// 32x32 pixel icons: Workspace database "chiclets" and R5 bookmark buttons.
// Names and intended subjects are listed in names.ts (ICON32_NAMES).
//
// Each icon is 32 rows of 32 PALETTE keys ("." transparent). Style: Windows
// 95 / Notes R4-R5 icons with a black outline, light from the top-left
// (white/light-gray highlights), gray/dark-gray shading to the bottom-right
// and a 1px gray drop shadow. The db-* subjects sit in the central ~28x28 area
// because the Workspace draws its own raised tile behind them; the bm-* icons
// are the large R5 bookmark-bar buttons. All artwork is original.
// ============================================================================

import type { Icon32Name } from "./names";
import type { PixelIcon } from "./types";

export const ICONS32: Record<Icon32Name, PixelIcon> = {
  // envelope over an in-tray, the mail file
  "db-mail": {
    size: 32,
    rows: [
      "................................",
      "................................",
      ".........kkkkkkkkkkkkkkkkkkk....",
      ".........kgghhhhhhhhhhhhhggkg...",
      ".........kssghhhhhhhhhhhgsskg...",
      "......kkkkkkkkkkkkkkkkkkkkhkg...",
      "......kddwwwwwwwwwwwwwwddkhkg...",
      "......khhdwwwwwwwwwwwwdhhkhkg...",
      "......kwwhddwwwwwwwwddhwwkhkg...",
      "......kwwwhhdwwwwwwdhhwwwkhkg...",
      "......kwwwwwhddwwddhwwwwwkhkg...",
      "......kwwwwwwhhddhhwwwwwwkhkg...",
      "......kwwwwwwwwhhwwwwwwwwkhkg...",
      "......kwwwwwwwhwwhwwwwwwwkhkg...",
      "......kwwwwwwhwwwwhwwwwwwkhkg...",
      "......kwwwwwhwwwwwwhwwwwwkhkg...",
      ".....kkwwwwhwwwwwwwwhwwwwkkkg...",
      "....kakwwwhwwwwwwwwwwhwwwkakg...",
      "...kankwwhwwwwwwwwwwwwhwwknak...",
      "..kannkwhwwwwwwwwwwwwwwhwknnak..",
      "..kkkkkkkkkkwwwwwwwwkkkkkkkkkkg.",
      "..kaaaaaaaaakwwwwwwkaaaaaaaabkg.",
      "..kaBBBBBBBBakkkkkkaBBBBBBBBbkg.",
      "..kaBBBBBBBBBaaaaaaBBBBBBBBBbkg.",
      "..kaBBBBBBBBBBBBBBBBBBBBBBBBbkg.",
      "..kaBBBBBBBBBBBBBBBBBBBBBBBBbkg.",
      "..kaBBBBBBBBBBBBBBBBBBBBBBBBbkg.",
      "..kbbbbbbbbbbbbbbbbbbbbbbbbbbkg.",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkkkg.",
      "...gggggggggggggggggggggggggggg.",
      "................................",
      "................................",
    ],
  },
  // calendar page with rings
  "db-calendar": {
    size: 32,
    rows: [
      "................................",
      "................................",
      ".......kk.....kk.....kk.........",
      "......kwdk...kwdk...kwdk........",
      "......kgdkg..kgdkg..kgdkg.......",
      "...kkkkgdkkkkkgdkkkkkgdkkkk.....",
      "...kiikddkiiikddkiiikddkiikg....",
      "...kiRRkkRRRRRkkRRRRRkkRRRkkk...",
      "...kiRRRRRRRRRRRRRRRRRRRRRkskg..",
      "...kiRRRRRRRRRRRRRRRRRRRRRkskg..",
      "...kiRRRRRRRRRRRRRRRRRRRRRkskg..",
      "...krrrrrrrrrrrrrrrrrrrrrrkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...khhhhhhhhhhhhhhhhhhhhhhkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...khhhhhhhhhhhhhhhhhhhhhhkskg..",
      "...kwwwhwwhwwhRRhwwhwwhwwwkskg..",
      "...kwwwhwwhwwhRRhwwhwwhwwwkskg..",
      "...khhhhhhhhhhhhhhhhhhhhhhkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...khhhhhhhhhhhhhhhhhhhhhhkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...kwwwhwwhwwhwwhwwhwwhwwwkskg..",
      "...kkkkkkkkkkkkkkkkkkkkkkkkskg..",
      "....gksssssssssssssssssssssskg..",
      ".....kkkkkkkkkkkkkkkkkkkkkkkkg..",
      "......gggggggggggggggggggggggg..",
      "................................",
      "................................",
    ],
  },
  // clipboard with check marks
  "db-todo": {
    size: 32,
    rows: [
      "................................",
      ".............kkkkkk.............",
      "............kwwhhhsk............",
      ".....kkkkkkkkwkkkkskkkkkkkk.....",
      "....koooookkkhhhhhgkkkoooork....",
      "....kozzzkwwhhhhhhhhhgkzzzrkg...",
      "....kozkkkhsssssssssggkkkzrkg...",
      "....kozkwkkkkkkkkkkkkkkhkzrkg...",
      "....kozkwwwwwwwwwwwwwwwhkzrkg...",
      "....kozkwwwwwwwwwwwwwwwhkzrkg...",
      "....kozkwwwwwwwwGwwwwwwhkzrkg...",
      "....kozkwwwwwwwGGwwwwwwhkzrkg...",
      "....kozkwGwwwwGGewggggghkzrkg...",
      "....kozkwGGwwGGewwwwwwwhkzrkg...",
      "....kozkweGGGGewwwsssswhkzrkg...",
      "....kozkwweGGewwwwwwwwwhkzrkg...",
      "....kozkwwwwwwwwGwwwwwwhkzrkg...",
      "....kozkwwwwwwwGGwwwwwwhkzrkg...",
      "....kozkwGwwwwGGewggggghkzrkg...",
      "....kozkwGGwwGGewwwwwwwhkzrkg...",
      "....kozkweGGGGewwwssswwhkzrkg...",
      "....kozkwweGGewwwwwwwwwhkzrkg...",
      "....kozkwwwwwwwwGwwwwwwhkzrkg...",
      "....kozkwwwwwwwGGwwwwwwhkzrkg...",
      "....kozkwGwwwwGGewggggghkzrkg...",
      "....kozkwGGwwGGewwwwwwwhkzrkg...",
      "....kozkheGGGGehhhsssshhkzrkg...",
      "....kozkkkeGGekkkkkkkkkkkzrkg...",
      "....krrrrrrrrrrrrrrrrrrrrrrkg...",
      ".....kkkkkkkkkkkkkkkkkkkkkkgg...",
      "......gggggggggggggggggggggg....",
      "................................",
    ],
  },
  // open address book with index tabs
  "db-addressbook": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "................................",
      "................................",
      ".....kkkkkk........kkkkkk.......",
      "....kwwwwwwkk....kkwwwwwwk......",
      "...kwwwwwwwwwk..kwwwwwwwwwkkk...",
      "...kwwwwwwwwwhkkwwwwwwwwwwiiRk..",
      "..kkwwwkkkwwwhshwggggggggwRRrkg.",
      ".kRkwwkuuukwwhshwwwwwwwwwwRRrkg.",
      ".kRkwwkuuzkwwhshwsssssswwwkkkgg.",
      ".kRkwwwkzkwwwhshwwwwwwwwwwkkkg..",
      ".kRkwkkBBBkkwhshwwwwwwwwwwffYk..",
      ".kRkkBBBBBBbkhshwggggggggwYYvkg.",
      ".kRkkBBBBBBbkhshwwwwwwwwwwYYvkg.",
      ".kRkkkkkkkkkkhshwssssswwwwkkkgg.",
      ".kRkwwwwwwwwwhshwwwwwwwwwwkkkg..",
      ".kRkwwwwwwwwwhshwwwwwwwwwwllGk..",
      ".kRkggggggggwhshwggggggggwGGekg.",
      ".kRkwwwwwwwwwhshwwwwwwwwwwGGekg.",
      ".kRkssssssswwhshwssssssswwkkkgg.",
      ".kRkwwwwwwwwwhshwwwwwwwwwwkkkg..",
      ".kRksssssssswhshwwwwwwwwwwaaBk..",
      ".kRkwwwwwwwwwhshwwwwwwwwwwBBbkg.",
      ".kRkkkkkkkkkkkshkkkkkkkkkkBBbkg.",
      ".kRhhhhhhhhhhhkkhhhhhhhhhhkkkgg.",
      ".kRggggggggggghhgggggggggggrkg..",
      "..kkkkkkkkkkkkggkkkkkkkkkkkkgg..",
      "...gggggggggggggggggggggggggg...",
      "................................",
      "................................",
      "................................",
    ],
  },
  // spiral notebook with pen
  "db-journal": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "......kkkkkkkkkkkkkkkkkkkkk.....",
      "...kkkkkwwwiwwwwwwwwwwwwwhkkk...",
      "..kswwhgkdwiwwwwwwwwwwwwwhknkg..",
      "...kkkkkwwwiwggwggggwgggwggnkg..",
      "....ggkaaaaiaaaaaaaaaaaaaaknkg..",
      "...kkkkkwwwiwwwwwwwwwwwwwhknkg..",
      "..kswwhgkdwiwggggwggwgggggkkkg..",
      "...kkkkkaaaiaaaaaaaaaaaaakBbkg..",
      "....ggkwwwwiwwwwwwwwwwwwkBbnkg..",
      "...kkkkkwwwiwgggwgggggwkBbnkkg..",
      "..kswwhgkdaiaaaaaaaaaakBbnknkg..",
      "...kkkkkwwwiwwwwwwwwwkBbnkknkg..",
      "....ggkwwwwiwwwwwwwwkYbnkhknkg..",
      "...kkkkkaaaiaaaaaaakivykaaknkg..",
      "..kswwhgkdwiwwwwwwkiRrkwwhknkg..",
      "...kkkkkwwwiwwwwwkiRrkwwwhknkg..",
      "....ggkaaaaiaaaakiRrkaaaaaknkg..",
      "...kkkkkwwwiwwwkiRrkwwwwwhknkg..",
      "..kswwhgkdwiwwkiRrkwwwwwwhknkg..",
      "...kkkkkaaaiakiRrkaaaaaaaaknkg..",
      "....ggkwwwwikgRrkwwwwwwwwhknkg..",
      "...kkkkkwwwkgdkkwwwwwwwwwhknkg..",
      "..kswwhgkdakdkkaaaaaaaaaaaknkg..",
      "...kkkkkwwwskkwwwwwwwwwwwhknkg..",
      "....ggkhhhkihhhhhhhhhhhhhhknkg..",
      "......kkkkkkkkkkkkkkkkkkkkknkg..",
      ".......gknnnnnnnnnnnnnnnnnnnkg..",
      "........kkkkkkkkkkkkkkkkkkkkkg..",
      ".........ggggggggggggggggggggg..",
      "................................",
    ],
  },
  // speech balloons, people talking
  "db-discussion": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "................................",
      "....kkkkkkkkkkkkkkk.............",
      "...kwwwwwwwwwwwwwwhk............",
      "..kwwwwwwwwwwwwwwwwhk...........",
      "..kwwwwwwwwwwwwwwwwhkg..........",
      "..kwwwgggggggggggwwhkg..........",
      "..kwwwwwwwwwwwwwwwwhkg..........",
      "..kwwwggggggggggggwhkg..........",
      "..kwwwwwwwwwwwwwwwwhkg..........",
      "..kwwwgggggggkkkkkkkkkkkkkkk....",
      "..kwwwwwwwwwkffffffffffffffvk...",
      "..khwwwwwwwkfYYYYYYYYYYYYYYYvk..",
      "...khwwwwwhkfYYYYYYYYYYYYYYYvkg.",
      "....kkwwwhkkfYYyyyyyyyyyyyYYvkg.",
      ".....kwwhkgkfYYYYYYYYYYYYYYYvkg.",
      "....kwwhkggkfYYyyyyyyyyyyyYYvkg.",
      "....kwhkgg.kfYYYYYYYYYYYYYYYvkg.",
      "...kkkkgg..kfYYyyyyyyyYYYYYYvkg.",
      "....gggg...kfYYYYYYYYYYYYYYYvkg.",
      "...........kfYYYYYYYYYYYYYYYvkg.",
      "...........kvYYYYYYYYYYYYYYYvkg.",
      "............kvvvvvvvvYYYYYvvkgg.",
      ".............kkkkkkkkkYYYYvkgg..",
      "..............ggggggggkYYYvkg...",
      ".......................kYYvkg...",
      "........................kYvkg...",
      ".........................kkkk...",
      "..........................gggg..",
      "................................",
      "................................",
    ],
  },
  // book with a large question mark
  "db-help": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "................................",
      "....kkkkkkkkkkkkkkkkkkk.........",
      "....kBBnBBBBBBBBBBBBBBkk........",
      "....kBbnbbbbbbbbbbbbbnkwk.......",
      "....kBbnbbbkkkkkkkkbbnkwhk......",
      "....kBbnbbkkwwwwwwkkbnkwhnk.....",
      "....kBbnbkkwYYYYYYYkknkwhnkg....",
      "....kBbnbkwYYYkkYYYvknkwhnkg....",
      "....kBbnbkwYYkkkkYYvknkwhnkg....",
      "....kBbnbkvvvkbbkYYvknkwhnkg....",
      "....kBbnbkkkkkbkkYYvknkwhnkg....",
      "....kBbnbbbbbbkkwYYvknkwhnkg....",
      "....kBbnbbbbbkkwYYvkknkwhnkg....",
      "....kBbnbbbbbkwYYvkkbnkwhnkg....",
      "....kBbnbbbbbkwYvkkbbnkwhnkg....",
      "....kBbnbbbbbkvvvkbbbnkwhnkg....",
      "....kBbnbbbbbkkkkkbbbnkwhnkg....",
      "....kBbnbbbbbkwYvkbbbnkwhnkg....",
      "....kBbnbbbbbkvvvkbbbnkwhnkg....",
      "....kBbnbbbbbkkkkkbbbnkwhnkg....",
      "....kBbnbbbbbbbbbbbbbnkwhnkg....",
      "....kBnnnnnnnnnnnnnnnnkwhnkg....",
      "....kkkkkkkkkkkkkkkkkkkwhnkg....",
      ".....kwwwwwwwwwwwwwwwwwwhnkg....",
      "......khhhhhhhhhhhhhhhhhhnkg....",
      ".......knnnnnnnnnnnnnnnnnnkg....",
      "........kkkkkkkkkkkkkkkkkkkg....",
      ".........ggggggggggggggggggg....",
      "................................",
      "................................",
    ],
  },
  // house (home page)
  "db-welcome": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "..................kkkk..........",
      "..................khskg.........",
      "..................kRrkg.........",
      "..................kRrkg.........",
      ".................kkRrkk.........",
      "..............kkkikRrkRk........",
      "...........kkkiiiRRRRRRRk.......",
      "........kkkiiiRRRRRRRrrrRk......",
      ".......kRkiRRRRRRRrrrRRRRRk.....",
      "......kRwRkRRRRrrrRRRRRRRRRk....",
      ".....kRwffRkrrrRRRRRRRRRrrrkk...",
      "....kRwfkffRkRRRRRRRRrrrkkkkgg..",
      "...kRwfkakffRkRRRRrrrkkkzzzkg...",
      "..kRwfffkffffRkrrrkkkzzzuuukg...",
      ".kRkwffffffffkRkkkzzzuuukkukg...",
      ".kkkwffffffffkzzzzuuuukkakukg...",
      "..gkwffffffffkuuuukkuukwBkukg...",
      "...kwffffffffkuukkakuukaBkukg...",
      "...kwfkkkkkffkuukwBkuukBbkukg...",
      "...kwfkozzkffkuukaBkuukbkkukg...",
      "...kwfkozzkffkuukBbkuukkuuukg...",
      "...kwfkozzkffkuukbkkuuuuuuukg...",
      "...kwfkozYkffkuukkuuuuuuuukkg...",
      "...kwfkozzkffkuuuuuuuuukkkggg...",
      "...kwfkozzkffkuuuuuukkkgggg.....",
      "...kwfkozzkffkuuukkkgggg........",
      "...kkkkkkkkkkkkkkgggg...........",
      "....gggggggggggggg..............",
      "................................",
      "................................",
    ],
  },
  // two computers with arrows between them
  "db-replicator": {
    size: 32,
    rows: [
      "................................",
      "...kkkkkkkkkkk..................",
      "..kwwwwwwwwwwwkkkkkkkkk.........",
      "..kwdddddddddgklllllllllk.......",
      "..kwdcccttttwgkGGGGGGGGGlk......",
      "..kwdcttttttwgkeeeeeeeGlGek.....",
      "..kwdtttttttwgkkkkkkkkklGekg....",
      "..kwdtttttttwgkgggggggklGekg....",
      "..kwdtttttttwgkg......klGekg....",
      "..kwdwwwwwwwwgkg...kkkklGekkkk..",
      "..kwggggggggggkg....kllllllekgg.",
      "...kkkkkkkkkkkgg.....kGGGGekgg..",
      "....kkkgggkkkgg.......kGGekgg...",
      "....khhhhhhgkg.........kekgg....",
      "....kkkkkkkkkg..........kgg.....",
      ".....ggggggggg...........g......",
      "..................kkkkkkkkkkk...",
      ".......k.........kwwwwwwwwwwwk..",
      "......klk........kwdddddddddgkg.",
      ".....klGGk.......kwdcccttttwgkg.",
      "....klGGGGk......kwdcttttttwgkg.",
      "...kleeeeeek.....kwdtttttttwgkg.",
      "..kkkklGekkkk....kwdtttttttwgkg.",
      "...ggklGekgggg...kwdtttttttwgkg.",
      ".....klGekg......kwdwwwwwwwwgkg.",
      ".....klGekkkkkkkkkwggggggggggkg.",
      ".....klGeGlllllllgkkkkkkkkkkkgg.",
      "......keGGGGGGGGGg.kkkgggkkkgg..",
      ".......keeeeeeeeeg.khhhhhhgkg...",
      "........gkkkkkkkkg.kkkkkkkkkg...",
      "..........gggggggg..ggggggggg...",
      "................................",
    ],
  },
  // thick book with a globe (Domino Directory)
  "db-directory": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "...kkkkkkkkkkkkkkkkk............",
      "...kBBnBBBBBBBBBBBBkk...........",
      "...kBbnbbbbbbbbbbbnkwk..........",
      "...kBbnbYYYYYYYYYYnkwhk.........",
      "...kBbnbYvvvvvvvvvnkwhwk........",
      "...kBbnbYvvvvvvvvvnkwhwhk.......",
      "...kBbnbYvvvvvvvvvnkwhwhnk......",
      "...kBbnbbnnnnnnnnnnkwhwhnkg.....",
      "...kBbnbbbbbbbbbbbnkwhwhnkg.....",
      "...kBbnbbbbbbbbbbbnkwhwhnkg.....",
      "...kBbnbbbbbbbbbbbnkwhwhnkg.....",
      "...kBbnbbbbbbbbbbbnkwhwhnkg.....",
      "...kBbnbbbbbbbbbbbnkwhwhnkg.....",
      "...kBbnbbbbbbbbbbbnkkkkkkkg.....",
      "...kBbnbbbbbbbbbbbkkaaaaakk.....",
      "...kBbnbbbbbbbbbbkaaalGGaaBk....",
      "...kBbnbbbbbbbbbkaalGGGGGaBBk...",
      "...kBbnbbbbbbbbbkalGGGGGBBBBkg..",
      "...kBbnbbbbbbbbkaaBGGGGBBBGGbk..",
      "...kBnnnnnnnnnnkaBBBGGBBBGGGbkg.",
      "...kkkkkkkkkkkkkaBBBBGGBBBGGbkg.",
      "....kwwwwwwwwwwkBBBBBGGGBBBebkg.",
      ".....khhhhhhhhhkBBBBBBGGGBBbbkg.",
      "......kwwwwwwwwwkBBBBBGGGBbbkgg.",
      ".......khhhhhhhhkBBBBBBGebbbkg..",
      "........knnnnnnnnkBBBBBebbbkgg..",
      ".........kkkkkkkkkkkbbbbbkkgg...",
      "..........ggggggggggkkkkkggg....",
      ".....................ggggg......",
      "................................",
    ],
  },
  // out-tray with envelopes (Outgoing Mail)
  "db-outbox": {
    size: 32,
    rows: [
      "................................",
      "..................kkkkkkkkkkk...",
      "...................kellllllekg..",
      "....................keGGGGGekg..",
      ".....................klGGGGekg..",
      "........kkkkkkkkkkkkkklGGGGekg..",
      "........kghhhhhhhhhhklGGGGGekg..",
      "........ksghhhhhhhhklGGGeeGekg..",
      "........khsghhhhhhklGGGekkeekg..",
      "....kkkkkkkkkkkkkklGGGekggkekg..",
      "....kdwwwwwwwwwwklGGGekkg..kkg..",
      "....khdwwwwwwwwklGGGekhkg...kg..",
      "....kwhdwwwwwwklGGGekhhkg....g..",
      "....kwwhddwwwklGGGekhhhkg.......",
      "....kwwwhhdwklGGGekkhhhkg.......",
      "....kwwwwwhklGGGekwkhhhkg.......",
      "....kwwwwwklGGGekwwkhhhkg.......",
      "....kkwwwklGGGekwwwkhhhkk.......",
      "....kwwwwkeGGekwwwwkhhhkgk......",
      "...kwwwwwwkeekwwwwwkkkkkdgk.....",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkk....",
      "..kwwwwwwwwwwwwwwwwwwwwwwwgkg...",
      "..kwssssssskkkkkkkksssssssgkg...",
      "..kwsssssssddddddddsssssssgkg...",
      "..kwsssssssddddddddsssssssgkg...",
      "..kwssssssswwwwwwwwsssssssgkg...",
      "..kwssssssssssssssssssssssgkg...",
      "..kggggggggggggggggggggggggkg...",
      "..kkkkkkkkkkkkkkkkkkkkkkkkkkg...",
      "...gggggggggggggggggggggggggg...",
      "................................",
      "................................",
    ],
  },
  // plain database cylinder
  "db-generic": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "............kkkkkkkk............",
      ".........kkkwwwwwwwhkkk.........",
      ".......kkwwwhhhhhhhhhhhkk.......",
      "......kwwhhhhhhhhhhhhhhhhk......",
      ".....kwhhhhhhhhhhhhhhhhhhhk.....",
      ".....khhhhhhhhhhhhhhhhhhhskg....",
      ".....kghhhhhhhhhhhhhhhhssdkg....",
      ".....khgghhhhhhhhhhhsssdddkg....",
      ".....khwwggghhhhhhssdddggdkg....",
      ".....khwwhssggggggggsggggdkg....",
      ".....khwwhsssssssssssggggdkg....",
      ".....khwwhsssssssssssggggdkg....",
      ".....kgwwhsssssssssssggggdkg....",
      ".....kwgghsssssssssssggddgkg....",
      ".....khwwgggssssssssgddssdkg....",
      ".....khwwwhhgggggggghssggdkg....",
      ".....khwwhsshhhhhhhhsggggdkg....",
      ".....khwwhsssssssssssggggdkg....",
      ".....kgwwhsssssssssssggggdkg....",
      ".....kwgghsssssssssssggddgkg....",
      ".....khwwgggssssssssgddssdkg....",
      ".....khwwwhhgggggggghssggdkg....",
      ".....khwwhsshhhhhhhhsggggdkg....",
      ".....khwwhsssssssssssggggdkg....",
      "......kwwhsssssssssssggggkgg....",
      ".......kkhsssssssssssggkkgg.....",
      "........gkkksssssssskkkggg......",
      "..........ggkkkkkkkkgggg........",
      ".............gggggggg...........",
      "................................",
    ],
  },
  // file folders with a document (document library)
  "db-doclib": {
    size: 32,
    rows: [
      "................................",
      "................................",
      ".........kkkkkkk................",
      "........kvvvvvvvk...............",
      "........kvyyyyyykkkkkkkkkkkkk...",
      "........kvyyyyyyyvvvvvvvvvvvvk..",
      ".......kkkkkkkkkkyyyyyyyyyyyykg.",
      ".......kwwwwwwwwgkkkkkkkkkkkkkg.",
      ".......kwwwwwwwwghkYYYYYYYYYykg.",
      ".......kwggggggwghhkvvvvvvvvykg.",
      "...kkkkkwwwwwwwwggggkvvvvvvvykg.",
      "..kYYYYkwggggggggggwkvvvvvvvykg.",
      "..kYvvvkwwwwwwwwwwwwkkkkvvvvykg.",
      "..kYvvvkwggggggggwwwkYYYkvvvykg.",
      "..kYvvvkwwwwwwwwwwwwkvvvkvvvykg.",
      "..kYvvvkwwwwwwwwwwwwkvvvkvvvykg.",
      "..kkkkkkkkkkkkkkkkkkkkkkkvvvykg.",
      "..kffffffffffffffffffffvkvvvykg.",
      "..kfYYYYYYYYYYYYYYYYYYYvkyyyykg.",
      "..kfYYYYYYYYYYYYYYYYYYYvkkkkkkg.",
      "..kfYYYYYYYYYYYYYYYYYYYvkgggggg.",
      "..kfYYYYYYYYYYYYYYYYYYYvkg......",
      "..kfYYYYYYYYYYYYYYYYYYYvkg......",
      "..kfYYYYYYYYYYYYYYYYYYYvkg......",
      "..kfYYYYYYYYYYYYYYYYYYYvkg......",
      "..kfYYYYYYYYYYYYYYYYYYYvkg......",
      "..kfYYYYYYYYYYYYYYYYYYYvkg......",
      "..kvvvvvvvvvvvvvvvvvvvvvkg......",
      "..kkkkkkkkkkkkkkkkkkkkkkkg......",
      "...ggggggggggggggggggggggg......",
      "................................",
      "................................",
    ],
  },
  // folder with a gold star
  "bm-favorites": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "................................",
      "................................",
      "...kkkkkkkk.....................",
      "..kYYYYYYYYk....................",
      "..kYvvvvvvvkkkkkkkkkkkkkk.......",
      "..kYvvvvvvvvYYYYYYYYYYYYYk......",
      "..kYvvvvvvvvvvvvvvvvvvvvvkg.....",
      "..kkkkkkkkkkkkkkkkkkkkkkkkg.....",
      "..kfffffffffffffffffffffvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYYYvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYYYvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYYYvkg.....",
      "..kfYYYYYYYYYYYYYYYYYkYYvkg.....",
      "..kfYYYYYYYYYYYYYYYYkfkYvkg.....",
      "..kfYYYYYYYYYYYYYYYYkfkYvkg.....",
      "..kfYYYYYYYYYYYYYYYkffYkvkg.....",
      "..kfYYYYYYYYYYYYYYYkffYkvkg.....",
      "..kfYYYYYYYYYkkkkkkffYYYkkkkkk..",
      "..kfYYYYYYYYYYkffffffYYYYYYYkgg.",
      "..kfYYYYYYYYYYYkYffffYYYYYvkgg..",
      "..kfYYYYYYYYYYYYkYYYYYvvvvkgg...",
      "..kvvvvvvvvvvvvvvkYYYvoovkgg....",
      "..kkkkkkkkkkkkkkkkYYvvoookg.....",
      "...gggggggggggggkYYYvkooook.....",
      "................kYYvkgkoookg....",
      "...............kYYkggg.gkook....",
      "...............kYkgg.....kokg...",
      "...............kkgg.......kkg...",
      "................gg.........gg...",
      "................................",
    ],
  },
  // stack of database cylinders
  "bm-databases": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "................................",
      "......kkkkkk........kkkkkk......",
      "....kkwwwwwhkk....kkwwwwwhkk....",
      "...kwwhhhhhhhhk..kwwhhhhhhhhk...",
      "..khhhhhhhhhhhhkkhhhhhhhhhhhhk..",
      "..kghhhhhhhhssgkkghhhhhhhhssgkg.",
      "..khgghhhhssggdkkhgghhhhssggdkg.",
      "..khwwggggggggdkkhwwggggggggdkg.",
      "..khwwhsssssggdkkhwwhsssssggdkg.",
      "..kgwwhsssssgkkkkkkwhsssssggdkg.",
      "..khgghsssskkwwwwwhkksssssdddkg.",
      "..khwwggggkwwhhhhhhhhkggggggdkg.",
      "..khwwhsskhhhhhhhhhhhhksssggdkg.",
      "..khwwhsskghhhhhhhhssgksssggdkg.",
      "...kwwhsskhgghhhhssggdksssggkgg.",
      "....kkhsskhwwggggggggdkssskkgg..",
      ".....gkkkkhwwhsssssggdkkkkggg...",
      ".......ggkgwwhsssssggdkgggg.....",
      ".........khgghsssssdddkg........",
      ".........khwwggggggggdkg........",
      ".........khwwhsssssggdkg........",
      ".........kgwwhsssssggdkg........",
      ".........khgghsssssdddkg........",
      ".........khwwggggggggdkg........",
      ".........khwwhsssssggdkg........",
      "..........kwwhsssssggkgg........",
      "...........kkhssssskkgg.........",
      "............gkkkkkkggg..........",
      "..............gggggg............",
      "................................",
    ],
  },
  // folder with a right arrow
  "bm-more": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "................................",
      "................................",
      "...kkkkkkkk.....................",
      "..kYYYYYYYYk....................",
      "..kYvvvvvvvkkkkkkkkkkkkkk.......",
      "..kYvvvvvvvvYYYYYYYYYYYYYk......",
      "..kYvvvvvvvvvvvvvvvvvvvvvkg.....",
      "..kkkkkkkkkkkkkkkkkkkkkkkkg.....",
      "..kfffffffffffffffffffffvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYYYvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYYYvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYkYvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYkkvkg.....",
      "..kfYYYYYYYYYYYYYYYYYYklkkg.....",
      "..kfYYYYYYYYYYYYYYYYYYkllkg.....",
      "..kfYYYYYYYYYYYkkkkkkkkGGlk.....",
      "..kfYYYYYYYYYYYklllllllllllk....",
      "..kfYYYYYYYYYYYklGGGGGGGGGGGk...",
      "..kfYYYYYYYYYYYklGGGGGGGGGGGGk..",
      "..kfYYYYYYYYYYYklGGGGGGGGGGekgg.",
      "..kfYYYYYYYYYYYkeeeeeeeeeeekgg..",
      "..kvvvvvvvvvvvvkkkkkkkkGeekgg...",
      "..kkkkkkkkkkkkkkkkkkkkkGekgg....",
      "...gggggggggggggggggggkekgg.....",
      "......................kkgg......",
      "......................kgg.......",
      ".......................g........",
      "................................",
      "................................",
      "................................",
    ],
  },
  // clock
  "bm-history": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "............kkkkkkkk............",
      "..........kkwwwwwwwhkk..........",
      "........kkwwwwwwwwhhhhkk........",
      ".......kwwwwwwwwwwhhhhhhk.......",
      "......kwwwwwgggggggghhhhsk......",
      ".....kwwwwgghhhkkhwwgshsssk.....",
      "....kwwwwghgwwwkkwwwgwsssssk....",
      "....kwwwghwwwwwwwwwwwwwsssskg...",
      "...kwwwghwwwwwwwwwwwwwwwssssk...",
      "...kwwwggwwwwwwwwwwwwwkgwsggkg..",
      "..kwwwghwwkwwwwwwwwwkkkwwwgggk..",
      "..kwwwghwwkkkwwwwwwkkkwwwwgggkg.",
      "..kwwwghwwwkkkkwwkkkwwwwwwgggkg.",
      "..kwwwgkkwwwwkkgkkkwwwwkkwgggkg.",
      "..kwwwgkkwwwwwwkkwwwwwwkkwgggkg.",
      "..kwwwghwwwwwwwwwRwwwwwwwwgggkg.",
      "..kwhhgwwwwwwwwwwRwwwwwwwwdddkg.",
      "..khhhgwwwwwwwwwwwRwwwwwwwdddkg.",
      "...khhhggwwwwwwwwwwRwwwgwdddkgg.",
      "...khhhswwwwwwwwwwwRwwwwwdddkg..",
      "....khhhswwwwwwwwwwwRwwwdddkgg..",
      "....khhssswgwwwkkwwwgwwddddkg...",
      ".....kssssswwwwkkwwwwwddddkgg...",
      "......kssssswwwwwwwwdddddkgg....",
      ".......ksssgggggggddddddkgg.....",
      "........kksgggggggddddkkgg......",
      ".........gkkggggggddkkggg.......",
      "...........gkkkkkkkkggg.........",
      ".............gggggggg...........",
      "................................",
    ],
  },
  // grid of colored tiles
  "bm-workspace": {
    size: 32,
    rows: [
      "................................",
      "................................",
      "..kkkkkkkkkkkk...kkkkkkkkkkkk...",
      "..kiiiiiiiiirkg..kfffffffffvkg..",
      "..kiwwwwRRRRrkg..kfwwwwYYYYvkg..",
      "..kiwRRRRRRRrkg..kfwYYYYYYYvkg..",
      "..kiRRRRRRRRrkg..kfYYYYYYYYvkg..",
      "..kiRRRRRRRRrkg..kfYYYYYYYYvkg..",
      "..kiRRRRRRRRrkg..kfYYYYYYYYvkg..",
      "..kiRRRRRRRRrkg..kfYYYYYYYYvkg..",
      "..kiRRRRRRRRrkg..kfYYYYYYYYvkg..",
      "..kiRRRRRRRRrkg..kfYYYYYYYYvkg..",
      "..krrrrrrrrrrkg..kvvvvvvvvvvkg..",
      "..kkkkkkkkkkkkg..kkkkkkkkkkkkg..",
      "...gggggggggggg...gggggggggggg..",
      "................................",
      "................................",
      "..kkkkkkkkkkkk...kkkkkkkkkkkk...",
      "..klllllllllekg..kaaaaaaaaabkg..",
      "..klwwwwGGGGekg..kawwwwBBBBbkg..",
      "..klwGGGGGGGekg..kawBBBBBBBbkg..",
      "..klGGGGGGGGekg..kaBBBBBBBBbkg..",
      "..klGGGGGGGGekg..kaBBBBBBBBbkg..",
      "..klGGGGGGGGekg..kaBBBBBBBBbkg..",
      "..klGGGGGGGGekg..kaBBBBBBBBbkg..",
      "..klGGGGGGGGekg..kaBBBBBBBBbkg..",
      "..klGGGGGGGGekg..kaBBBBBBBBbkg..",
      "..keeeeeeeeeekg..kbbbbbbbbbbkg..",
      "..kkkkkkkkkkkkg..kkkkkkkkkkkkg..",
      "...gggggggggggg...gggggggggggg..",
      "................................",
      "................................",
    ],
  },
};
