// ============================================================================
// 16x16 pixel icons, group B: calendar, contacts, to do, notebook, discussion,
// text formatting, mood stamps, Notes 8 sidebar.
// Names and intended subjects are listed in names.ts (ICON16B_NAMES).
//
// Motifs used here:
//   calendar page  15px white page, red header with a dark edge, two binder
//                  rings; the cal-* view icons differ only in the page grid
//   "new" sparkle  4-point yellow star with an orange center, top right
//   person         tan head, blue shirt (green shirt for a second person)
//   arrows         green = navigation / move, blue = forward, purple = undo
//   text glyphs    black letterforms with a light-gray "h" halo so they stay
//                  legible on a navy selection
// ============================================================================

import type { Icon16BName } from "./names";
import type { PixelIcon } from "./types";

export const ICONS16B: Record<Icon16BName, PixelIcon> = {
  // calendar
  "cal-new": {
    size: 16,
    rows: [
      "............v...",
      "..kk.......kY...",
      "..kk.......YYY..",
      "kkkkkkkkkvYYoYYv",
      "kRkkRRRRRRRYYYk.",
      "kRRRRRRRRRRRYRk.",
      "krrrrrrrrrrrvrk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-today": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwswswswswswswk.",
      "ksssssRRssssssk.",
      "kwswsRRRrwswswk.",
      "kssssRRRrsssssk.",
      "kwswswrrswswswk.",
      "ksssssssssssssk.",
      "kwswswswswswswk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-day": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "ksssssssssssssk.",
      "kwwwwwwwwwwwwwk.",
      "ksssssssssssssk.",
      "kwwwwwwwwwwwwwk.",
      "kwwwwwwwwwwwwwk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-twodays": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwwwwwwswwwwwwk.",
      "kwwwwwwswwwwwwk.",
      "ksssssssssssssk.",
      "kwwwwwwswwwwwwk.",
      "ksssssssssssssk.",
      "kwwwwwwswwwwwwk.",
      "kwwwwwwswwwwwwk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-week": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-workweek": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwwswwswswwswwk.",
      "kwwswwswswwswwk.",
      "kwwswwswswwswwk.",
      "kwwswwswswwswwk.",
      "kwwswwswswwswwk.",
      "kwwswwswswwswwk.",
      "kwwswwswswwswwk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-twoweeks": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "ksssssssssssssk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kwswswswswswswk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-month": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwswswswswswswk.",
      "ksssssssssssssk.",
      "kwswswswswswswk.",
      "ksssssssssssssk.",
      "kwswswswswswswk.",
      "ksssssssssssssk.",
      "kwswswswswswswk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "cal-list": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwwwwwwwwwwwwwk.",
      "kwbbwggggggggwk.",
      "kwwwwwwwwwwwwwk.",
      "kwbbwggggggggwk.",
      "kwwwwwwwwwwwwwk.",
      "kwbbwggggggggwk.",
      "kwwwwwwwwwwwwwk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  recurrence: {
    size: 16,
    rows: [
      "................",
      "........b.......",
      ".......bBb......",
      "......bbBBb.....",
      "....bbBBBBBb....",
      "...bBBBBBBBb....",
      "...bBBbbBBb.....",
      "..bBBb.bBb......",
      "..bBBb..b.......",
      "..bBBb....bbbb..",
      "..bBBb....bBBb..",
      "...bBBbbbbBBb...",
      "...bBBBBBBBBb...",
      "....bbBBBBbb....",
      "......bbbb......",
      "................",
    ],
  },
  alarm: {
    size: 16,
    rows: [
      "................",
      ".kkk.......kkk..",
      "kYYYk.kkk.kYYYk.",
      "kYYkkkkkkkkkYvk.",
      ".kkRRRRRRRRRkk..",
      "..kRRwwwwwRRk...",
      ".kRwwwwkwwwwRk..",
      ".kRwwwwkwwwwRk..",
      ".kRwwwwkkkwwRk..",
      ".kRwwwwwwwwwRk..",
      ".kRwwwwwwwwwRk..",
      "..kRRwwwwwRRk...",
      "...kRRRRRRRk....",
      "....kkkkkkk.....",
      "...kk.....kk....",
      "................",
    ],
  },
  appointment: {
    size: 16,
    rows: [
      "................",
      ".....kkkkk......",
      "...kkwwkwwkk....",
      "..kwwwwwwwwwk...",
      "..kwwwwkwwwwk...",
      ".kwwwwwkwwwwwk..",
      ".kwwwwwkwwwwwk..",
      ".kkwwwwkkkkwkk..",
      ".kwwwwwwwwwwwk..",
      ".kwwwwwwwwwwsk..",
      "..kwwwwwwwwsk...",
      "..kwwwwwwwssk...",
      "...kkwwkwsskk...",
      ".....kkkkk......",
      "................",
      "................",
    ],
  },
  meeting: {
    size: 16,
    rows: [
      "................",
      "................",
      "..kkkk....kkkk..",
      ".kuuuuk..kuuuuk.",
      ".kuuuuk..kuuuuk.",
      ".kuuuuk..kuuuuk.",
      ".kuuuuk..kuuuuk.",
      "..kkkk....kkkk..",
      ".kBBBBk..kGGGGk.",
      "kBBBBBBkkGGGGGGk",
      "kBBBBBBkkGGGGGGk",
      "kBBBBBbkkGGGGGek",
      "kBBBBBbkkGGGGGek",
      "kkkkkkkkkkkkkkkk",
      "................",
      "................",
    ],
  },
  reminder: {
    size: 16,
    rows: [
      "................",
      "......kkkk......",
      ".....kiRRRk.....",
      ".kkkkkRRRRkkkkk.",
      ".kYYYkRRRrkYYvk.",
      ".kYYYYkkkkYYYvk.",
      ".kYYYYYYYYYYYvk.",
      ".kYggggggggYYvk.",
      ".kYYYYYYYYYYYvk.",
      ".kYggggggggggvk.",
      ".kYYYYYYYYYYYvk.",
      ".kYgggggYYYYYvk.",
      ".kYYYYYYYYYYYvk.",
      ".kvvvvvvvvvvvvk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  event: {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkkRRRRRRkkRk.",
      "kRRRkkkRRRRRRRk.",
      "krrrkGGkkrrrrrk.",
      "kwwwkGGGGkkwwwk.",
      "kwwwkGGGGGGkwwk.",
      "kwwwkGGGGkkwwwk.",
      "kwwwkGGkkwwwwwk.",
      "kwwwkkkwwwwwwwk.",
      "kwwwkwwwwwwwwwk.",
      "kwwwkwwwwwwwwwk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  anniversary: {
    size: 16,
    rows: [
      "................",
      "...kk......kk...",
      "..kYYk....kYYk..",
      "..kYvYk..kYvYk..",
      "...kkYYkkYYkk...",
      ".kkkkkkYYkkkkkk.",
      ".kiiiiiYviiiiik.",
      ".kRRRRRYvRRRRrk.",
      ".kkkkkkYvkkkkkk.",
      "..kRRRRYvRRRrk..",
      "..kRRRRYvRRRrk..",
      "..kRRRRYvRRRrk..",
      "..kRRRRYvRRRrk..",
      "..krrrrYvrrrrk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  invitation: {
    size: 16,
    rows: [
      ".........k...k..",
      ".........k...k..",
      ".......kkkkkkkkk",
      ".......kRkRRRkRk",
      ".......krrrrrrrk",
      ".......kwwwwwwwk",
      "kkkkkkkkwswswswk",
      "kdwwwwwkwwwwwwwk",
      "kwdwwwwkwswswswk",
      "kwwdwwwkkkkkkkkk",
      "kwwwdwwwdwwwk...",
      "kwwwwdwdwwwwk...",
      "kwwwwwdwwwwwk...",
      "kgggggggggggk...",
      "kkkkkkkkkkkkk...",
      "................",
    ],
  },
  accept: {
    size: 16,
    rows: [
      "................",
      ".............ee.",
      "............eGGe",
      "...........eGGGe",
      "..........eGGGe.",
      ".........eGGGe..",
      ".ee.....eGGGe...",
      "eGGe...eGGGe....",
      "eGGGe.eGGGe.....",
      ".eGGGeGGGe......",
      "..eGGGGGe.......",
      "...eGGGe........",
      "....eee.........",
      "................",
      "................",
      "................",
    ],
  },
  decline: {
    size: 16,
    rows: [
      "................",
      "................",
      ".RRR.......RRR..",
      "..RRR.....RRRrr.",
      "...RRR...RRRrr..",
      "....RRR.RRRrr...",
      ".....RRRRRrr....",
      "......RRRrr.....",
      ".....RRRRR......",
      "....RRRrRRR.....",
      "...RRRrr.RRR....",
      "..RRRrr...RRR...",
      ".RRRrr.....RRR..",
      "..rrr.......rrr.",
      "................",
      "................",
    ],
  },
  tentative: {
    size: 16,
    rows: [
      "................",
      ".....bbbbbb.....",
      "....bBBBBBBb....",
      "...bBBbbbbBBb...",
      "...bBBb..bBBb...",
      "....bb..bBBb....",
      ".......bBBb.....",
      "......bBBb......",
      "......bBBb......",
      ".......bb.......",
      "................",
      ".......bb.......",
      "......bBBb......",
      "......bBBb......",
      ".......bb.......",
      "................",
    ],
  },
  delegate: {
    size: 16,
    rows: [
      "................",
      "..kkk...........",
      ".kuuuk..........",
      ".kuuuk..........",
      ".kuuuk..........",
      "..kkk...........",
      ".kBBBk..........",
      "kBBBBBk.........",
      "kBBBBbk.....b...",
      "kBBBBbk.....bb..",
      "kkkkkkkbbbbbbBb.",
      ".......bBBBBBBBb",
      ".......bBBBBBBBb",
      ".......bbbbbbBb.",
      "............bb..",
      "............b...",
    ],
  },
  propose: {
    size: 16,
    rows: [
      "...kkkkk........",
      "..kwwkwwk.......",
      ".kwwwkwwwk......",
      "kwwwwkwwwwk.....",
      "kwwwwkwwwwk.....",
      "kkwwwkkkwkk.....",
      "kwwwwwwwwsk.p...",
      "kwwwwwwwwskpqp..",
      ".kwwwwwwskpqqqp.",
      "..kwwkwsk.ppqpp.",
      "...kkkkk...pqp..",
      "..........pqqp..",
      "........ppqqp...",
      "........pqqp....",
      "........ppp.....",
      "................",
    ],
  },
  scheduler: {
    size: 16,
    rows: [
      "................",
      "kkkkkkkkkkkkkkkk",
      "kwwwswwwswwwswwk",
      "kwBBBBBBswwwswwk",
      "kwbbbbbbswwwswwk",
      "kwwwswwwswwwswwk",
      "kwwwswRRRRRRRwwk",
      "kwwwswrrrrrrrwwk",
      "kwwwswwwswwwswwk",
      "kwwBBBBBBBswswwk",
      "kwwbbbbbbbswswwk",
      "kwwwswwwswwwswwk",
      "kwwwswwwsBBBBBwk",
      "kwwwswwwsbbbbbwk",
      "kkkkkkkkkkkkkkkk",
      "................",
    ],
  },
  snooze: {
    size: 16,
    rows: [
      "..........BBBBB.",
      ".............B..",
      "............B...",
      "...........B....",
      "..........BBBBB.",
      "................",
      ".........BBB....",
      "..kkkkk...B.....",
      ".kwwkwwk.BBB....",
      "kwwwkwwwk.......",
      "kwwwkwwwk.......",
      "kwwwkkkwk.......",
      "kwwwwwwsk.......",
      "kwwwwwwsk.......",
      ".kwwwwsk........",
      "..kkkkk.........",
    ],
  },

  // contacts
  person: {
    size: 16,
    rows: [
      "................",
      "......kkkk......",
      ".....kuuuuk.....",
      "....kuuuuuuk....",
      "....kuuuuuuk....",
      "....kuuuuuuk....",
      "....kuuuuuuk....",
      ".....kuuuuk.....",
      "....kkkkkkkk....",
      "...kBBBBBBBBk...",
      "..kBBBBBBBBBbk..",
      "..kBBBBBBBBBbk..",
      "..kBBBBBBBBBbk..",
      "..kBBBBBBBBBbk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  "person-new": {
    size: 16,
    rows: [
      "............v...",
      "............Y...",
      "....kkkk...YYY..",
      "...kuuuukvYYoYYv",
      "..kuuuuuuk.YYY..",
      "..kuuuuuuk..Y...",
      "..kuuuuuuk..v...",
      "..kuuuuuuk......",
      "...kuuuuk.......",
      "..kkkkkkkk......",
      ".kBBBBBBBBk.....",
      "kBBBBBBBBBbk....",
      "kBBBBBBBBBbk....",
      "kBBBBBBBBBbk....",
      "kBBBBBBBBBbk....",
      "kkkkkkkkkkkk....",
    ],
  },
  group: {
    size: 16,
    rows: [
      ".........kkk....",
      "........kuuuk...",
      ".......kuuuuuk..",
      ".......kuuuuuk..",
      ".......kuuuuuk..",
      "....kkk.kuuuk...",
      "...kuuukkkkkkk..",
      "..kuuuuukGGGGGk.",
      "..kuuuuukGGGGek.",
      "..kuuuuukGGGGek.",
      "...kuuukkkkkkkk.",
      "..kkkkkkk.......",
      ".kBBBBBBBk......",
      ".kBBBBBBbk......",
      ".kBBBBBBbk......",
      ".kkkkkkkkk......",
    ],
  },
  company: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkkk......",
      ".kssssssgk......",
      ".ksBsBsBgk......",
      ".kssssssgk......",
      ".ksBsBsBgkkkkkk.",
      ".kssssssgkssssk.",
      ".ksBsBsBgksBsBk.",
      ".kssssssgkssssk.",
      ".ksBsBsBgksBsBk.",
      ".kssssssgkssssk.",
      ".ksBsBsBgksBsBk.",
      ".kssssssgkssssk.",
      ".ksskkssgkssssk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  tag: {
    size: 16,
    rows: [
      "................",
      ".k..............",
      ".k..............",
      "..kk............",
      "....kkkkkk......",
      "....kYYYYvk.....",
      "....kYkkYYvk....",
      "....kYkYYYYvk...",
      "....kYYYYYYYvk..",
      "....kvYYYYYYYvk.",
      ".....kvYYYYYYYvk",
      "......kvYYYYYYvk",
      ".......kvYYYYvk.",
      "........kvYYvk..",
      ".........kvvk...",
      "..........kk....",
    ],
  },
  "by-name": {
    size: 16,
    rows: [
      "...hh...........",
      "..hkkh....bbb...",
      ".hkkkkh...bBb...",
      ".hkhhkh...bBb...",
      "hkkhhkkh..bBb...",
      "hkkkkkkh..bBb...",
      "hkkhhkkh..bBb...",
      "hkkhhkkh..bBb...",
      ".hhhhhh...bBb...",
      "hkkkkkkhbbbBbbb.",
      ".hhhhkkhbBBBBBb.",
      "...hkkh..bBBBb..",
      "..hkkh....bBb...",
      ".hkkhhh....b....",
      "hkkkkkkh........",
      ".hhhhhh.........",
    ],
  },
  "vcard-export": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "kkkkkkkkkkk.....",
      "kwwwwwwwwwk.....",
      "kwaaawwwwwk.e...",
      "kwauawggggk.ee..",
      "kwBBBwweeeeeeGe.",
      "kwBBBwgeGGGGGGGe",
      "kwwwwwweGGGGGGGe",
      "kkkkkkkeeeeeeGe.",
      "............ee..",
      "............e...",
      "................",
      "................",
    ],
  },
  "vcard-import": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "kkkkkkkkkkk.....",
      "kwwwwwwwwwk.....",
      "kwaaawwwwwe.....",
      "kwauawgggee.....",
      "kwBBBwwweGeeeeee",
      "kwBBBwgeGGGGGGGe",
      "kwwwwwweGGGGGGGe",
      "kkkkkkkkeGeeeeee",
      ".........ee.....",
      "..........e.....",
      "................",
      "................",
    ],
  },
  "write-memo": {
    size: 16,
    rows: [
      "................",
      ".............kk.",
      "............kiik",
      "...........ksiik",
      "..........kYsgk.",
      ".........kYYvk..",
      "kkkkkkkkkYYvk...",
      "kdwwwwwkYYvkk...",
      "kwdwwwkYYvkwk...",
      "kwwdwkuuvkwwk...",
      "kwwwkuuukwwwk...",
      "kwwwkkukwwwwk...",
      "kwwwwkkwwwwwk...",
      "kgggggggggggk...",
      "kkkkkkkkkkkkk...",
      "................",
    ],
  },
  "business-card": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kwwwwwwwwwwwwk.",
      ".kwaaaawwwwwwwk.",
      ".kwauuawggggggk.",
      ".kwauuawwwwwwwk.",
      ".kwBBBBwggggwwk.",
      ".kwBBBBwwwwwwwk.",
      ".kwwwwwwgggggwk.",
      ".kwwwwwwwwwwwwk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
      "................",
    ],
  },

  // to do
  "todo-new": {
    size: 16,
    rows: [
      "............v...",
      ".....kkkk...Y...",
      "....khhssk.YYY..",
      ".kkkksssgvYYoYYv",
      ".kzzkkkkkkzYYY..",
      ".kzwwwwwwwwzY...",
      ".kzwwwwewwwzv...",
      ".kzewwewwggzk...",
      ".kzweewwwwwzk...",
      ".kzwwwwwwwwzk...",
      ".kzwwwwewwwzk...",
      ".kzewwewwggzk...",
      ".kzweewwwwwzk...",
      ".kzwwwwwwwwzk...",
      ".kzzzzzzzzzzk...",
      ".kkkkkkkkkkkk...",
    ],
  },
  complete: {
    size: 16,
    rows: [
      "................",
      "................",
      ".............ee.",
      "............eGGe",
      "kkkkkkkkkkkeGGGe",
      "kwwwwwwwwweGGGe.",
      "kwwwwwwwweGGGe..",
      "kwwwwwwweGGGe...",
      "kweewwweGGGe....",
      "keGGeweGGGek....",
      "keGGGeGGGesk....",
      "kweGGGGGewsk....",
      "kwweGGGewwsk....",
      "kwwweeewwwsk....",
      "kwssssssssss....",
      "kkkkkkkkkkkk....",
    ],
  },
  incomplete: {
    size: 16,
    rows: [
      "........pqp.....",
      ".......pqqpppp..",
      "......pqqqqqqqp.",
      "......pqqqqqqqqp",
      "kkkkkkkpqqpppqqp",
      "kwwwwwwwpqpkpqqp",
      "kwwwwwwwwpskpqqp",
      "kwwwwwwwwwspqqqp",
      "kwwwwwwwwwskppp.",
      "kwwwwwwwwwsk....",
      "kwwwwwwwwwsk....",
      "kwwwwwwwwwsk....",
      "kwwwwwwwwwsk....",
      "kwwwwwwwwwsk....",
      "kwssssssssss....",
      "kkkkkkkkkkkk....",
    ],
  },
  overdue: {
    size: 16,
    rows: [
      "....kkkkk.......",
      "..kkwwkwwkk.....",
      ".kwwwwwwwwwk....",
      ".kwwwwkwwwwk....",
      "kwwwwwkwwwwwk...",
      "kwwwwwkwwwwwk...",
      "kkwwwwkkkkwkk...",
      "kwwwwwwwwwwwk...",
      "kwwwwwwwwwwsk...",
      ".kwwwwwwwwskkk..",
      ".kwwwwwwwskRRRk.",
      "..kkwwkwskRRwRRk",
      "....kkkkkkRRwRRk",
      ".........kRRRRRk",
      "..........kRwRk.",
      "...........kkk..",
    ],
  },
  "by-status": {
    size: 16,
    rows: [
      "................",
      "................",
      "..........kkkk..",
      "..........kGGk..",
      "..........kGek..",
      "......kkkkkGek..",
      "......kYYkkGek..",
      "......kYvkkGek..",
      "..kkkkkYvkkGek..",
      "..kRRkkYvkkGek..",
      "..kRrkkYvkkGek..",
      "..kRrkkYvkkGek..",
      "..kRrkkYvkkGek..",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  "due-date": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwswswswswswswk.",
      "ksssssssssssssk.",
      "kwswswswswswswk.",
      "kssssssssssssRk.",
      "kwswswswswswRRk.",
      "kssssssssssRRRk.",
      "kwswswswswRRRRk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },

  // notebook
  "note-new": {
    size: 16,
    rows: [
      "............v...",
      "............Y...",
      "..kkkkkkkkkYYY..",
      "kkkwwwwwwvYYoYYv",
      "..kwwiwwwwwYYY..",
      "kkkaaiaaaaaaY...",
      "..kwwiwwwwwwv...",
      "kkkwwiwwwwwwk...",
      "..kaaiaaaaaak...",
      "kkkwwiwwwwwwk...",
      "..kwwiwwwwwwk...",
      "kkkaaiaaaaaak...",
      "..kwwiwwwwwwk...",
      "kkkwwiwwwwwwk...",
      "..kaaiaaaaaak...",
      "..kkkkkkkkkkk...",
    ],
  },
  note: {
    size: 16,
    rows: [
      "................",
      "..kkkkkkkk......",
      "..kwwwwwwkk.....",
      "..kwwwwwwkhk....",
      "..kwwwwwwkhhk...",
      "..kwwwwwwkkkkk..",
      "..kwwiwwwwwwwk..",
      "..kaaiaaaaaaak..",
      "..kwwiwwwwwwwk..",
      "..kaaiaaaaaaak..",
      "..kwwiwwwwwwwk..",
      "..kaaiaaaaaaak..",
      "..kwwiwwwwwwwk..",
      "..kaaiaaaaaaak..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },

  // discussion
  "topic-new": {
    size: 16,
    rows: [
      "............v...",
      "............Y...",
      "..kkkkkkkkkYYY..",
      ".kwwwwwwwvYYoYYv",
      "kwwwwwwwwwwYYY..",
      "kwggggggggggYk..",
      "kwwwwwwwwwwwvk..",
      "kwggggggggggwk..",
      "kwwwwwwwwwwwwk..",
      "kwgggggggwwwwk..",
      ".kwwwwwwwwwwk...",
      "..kwwkkkkkkk....",
      "..kwk...........",
      ".kwk............",
      ".kk.............",
      "................",
    ],
  },
  topic: {
    size: 16,
    rows: [
      "................",
      "...kkkkkkkkkk...",
      "..kwwwwwwwwwwk..",
      ".kwwwwwwwwwwwwk.",
      ".kwggggggggggwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwggggggggggwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwgggggggwwwwk.",
      "..kwwwwwwwwwwk..",
      "...kwwkkkkkkk...",
      "...kwk..........",
      "..kwk...........",
      "..kk............",
      "................",
      "................",
    ],
  },
  "response-new": {
    size: 16,
    rows: [
      "................",
      ".bbb............",
      ".bBb............",
      ".bBb..b.........",
      ".bBbbbBb........",
      ".bBBBBBBb.......",
      ".bbbbbBb........",
      "......b.........",
      ".......kkkkkkkk.",
      "......kwwwwwwwwk",
      "......kwggggggwk",
      "......kwwwwwwwwk",
      "......kwggggwwwk",
      ".......kwkkkkkk.",
      ".......kk.......",
      "................",
    ],
  },
  thread: {
    size: 16,
    rows: [
      ".kkkkkkk........",
      "kwwwwwwwk.......",
      "kwgggggwk.......",
      ".kwkkkkk........",
      ".kk.............",
      "....kkkkkkk.....",
      "...kwwwwwwwk....",
      "...kwgggggwk....",
      "....kwkkkkk.....",
      "....kk..........",
      ".......kkkkkkk..",
      "......kwwwwwwwk.",
      "......kwgggggwk.",
      ".......kwkkkkk..",
      ".......kk.......",
      "................",
    ],
  },
  "by-author": {
    size: 16,
    rows: [
      ".......kkkkkkkk.",
      "......kwwwwwwwwk",
      "......kwggggggwk",
      "......kwwwwwwwwk",
      "......kwggggwwwk",
      ".......kwkkkkkk.",
      "..kkk..kk.......",
      ".kuuuk..........",
      ".kuuuk..........",
      ".kuuuk..........",
      "..kkk...........",
      ".kBBBk..........",
      "kBBBBBk.........",
      "kBBBBbk.........",
      "kBBBBbk.........",
      "kkkkkkk.........",
    ],
  },

  // text formatting / edit SmartIcons
  "fmt-bold": {
    size: 16,
    rows: [
      "................",
      "................",
      "....hhhhhhh.....",
      "...hkkkkkkkh....",
      "...hkkkhhkkkh...",
      "...hkkkhhkkkh...",
      "...hkkkhhkkkh...",
      "...hkkkkkkkhh...",
      "...hkkkhhhkkkh..",
      "...hkkkh.hkkkh..",
      "...hkkkh.hkkkh..",
      "...hkkkhhhkkkh..",
      "...hkkkkkkkkh...",
      "....hhhhhhhh....",
      "................",
      "................",
    ],
  },
  "fmt-italic": {
    size: 16,
    rows: [
      "................",
      "................",
      "......hhhhhh....",
      ".....hkkkkkkh...",
      "......hhkkkh....",
      ".......hkkkh....",
      "......hkkkh.....",
      "......hkkkh.....",
      ".....hkkkh......",
      ".....hkkkh......",
      "....hkkkh.......",
      "...hhkkkh.......",
      "..hkkkkkkh......",
      "...hhhhhh.......",
      "................",
      "................",
    ],
  },
  "fmt-underline": {
    size: 16,
    rows: [
      "................",
      "...hhh...hhh....",
      "..hkkkh.hkkkh...",
      "..hkkkh.hkkkh...",
      "..hkkkh.hkkkh...",
      "..hkkkh.hkkkh...",
      "..hkkkh.hkkkh...",
      "..hkkkh.hkkkh...",
      "..hkkkhhhkkkh...",
      "...hkkkkkkkh....",
      "....hkkkkkh.....",
      "..hhhhhhhhhhh...",
      ".hkkkkkkkkkkkh..",
      "..hhhhhhhhhhh...",
      "................",
      "................",
    ],
  },
  "fmt-strike": {
    size: 16,
    rows: [
      "................",
      "................",
      ".....hhhhhh.....",
      "....hkkkkkkh....",
      "...hkkkhhkkkh...",
      "...hkkkhhhhh....",
      "..hhhkkkkhhhhh..",
      ".hkkkkkkkkkkkkh.",
      "..hhhhhkkkkhhh..",
      "....hhhhhkkkh...",
      "...hkkkhhkkkh...",
      "....hkkkkkkh....",
      ".....hhhhhh.....",
      "................",
      "................",
      "................",
    ],
  },
  "fmt-bullets": {
    size: 16,
    rows: [
      "................",
      "................",
      "..hh............",
      ".hkkh.gggggggg..",
      ".hkkh...........",
      "..hh............",
      "..hh............",
      ".hkkh.gggggggg..",
      ".hkkh...........",
      "..hh............",
      "..hh............",
      ".hkkh.gggggggg..",
      ".hkkh...........",
      "..hh............",
      "................",
      "................",
    ],
  },
  "fmt-numbers": {
    size: 16,
    rows: [
      "..h.............",
      ".hkh............",
      "hkkh..gggggggg..",
      ".hkh............",
      "hkkkh...........",
      ".hhh............",
      "hkkh............",
      ".hhkh.gggggggg..",
      ".hkh............",
      "hkkkh...........",
      ".hhh............",
      "hkkkh...........",
      ".hkkh.gggggggg..",
      ".hhkh...........",
      "hkkkh...........",
      ".hhh............",
    ],
  },
  "fmt-indent": {
    size: 16,
    rows: [
      "................",
      "................",
      ".gggggggggggggg.",
      "................",
      "................",
      "...b....ggggggg.",
      "...bb...........",
      "bbbbBb..........",
      "bBBBBBb.ggggggg.",
      "bbbbBb..........",
      "...bb...........",
      "...b....ggggggg.",
      "................",
      "................",
      ".gggggggggggggg.",
      "................",
    ],
  },
  "fmt-outdent": {
    size: 16,
    rows: [
      "................",
      "................",
      ".gggggggggggggg.",
      "................",
      "................",
      "...b....ggggggg.",
      "..bb............",
      ".bBbbbb.........",
      "bBBBBBb.ggggggg.",
      ".bBbbbb.........",
      "..bb............",
      "...b....ggggggg.",
      "................",
      "................",
      ".gggggggggggggg.",
      "................",
    ],
  },
  "fmt-left": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "..gggggggggggg..",
      "................",
      "..gggggggg......",
      "................",
      "..gggggggggggg..",
      "................",
      "..gggggggg......",
      "................",
      "..gggggggggggg..",
      "................",
      "..gggggggg......",
      "................",
      "................",
    ],
  },
  "fmt-center": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "..gggggggggggg..",
      "................",
      "....gggggggg....",
      "................",
      "..gggggggggggg..",
      "................",
      "....gggggggg....",
      "................",
      "..gggggggggggg..",
      "................",
      "....gggggggg....",
      "................",
      "................",
    ],
  },
  "fmt-right": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "..gggggggggggg..",
      "................",
      "......gggggggg..",
      "................",
      "..gggggggggggg..",
      "................",
      "......gggggggg..",
      "................",
      "..gggggggggggg..",
      "................",
      "......gggggggg..",
      "................",
      "................",
    ],
  },
  "fmt-color": {
    size: 16,
    rows: [
      "......hhh.......",
      ".....hkkkh......",
      ".....hkkkh......",
      "....hkkkkkh.....",
      "....hkkhkkh.....",
      "...hkkkhkkkh....",
      "...hkkhhhkkh....",
      "..hkkkkkkkkkh...",
      "..hkkhhhhhkkh...",
      ".hkkkh...hkkkh..",
      ".hhhhhhhhhhhhhh.",
      "hkkkkkkkkkkkkkkh",
      "hkRRRRRRRRRRRRkh",
      "hkRRRRRRRRRRRRkh",
      "hkkkkkkkkkkkkkkh",
      ".hhhhhhhhhhhhhh.",
    ],
  },
  "fmt-font": {
    size: 16,
    rows: [
      "................",
      "....hh..........",
      "...hkkh.........",
      "...hkkh.........",
      "..hkkkkh........",
      "..hkhkkh...hhh..",
      ".hkkhhkkh.hkkkh.",
      ".hkkhhkkhhkhhkkh",
      ".hkkkkkkh.hhkkkh",
      "hkkhhhhkkhkkhkkh",
      "hkkh..hkkhkkhkkh",
      "kkkkhhkkkkhkkhkk",
      "hhhh..hhhh.hh.hh",
      "................",
      "................",
      "................",
    ],
  },
  cut: {
    size: 16,
    rows: [
      "................",
      "....k......k....",
      "....kk....kk....",
      ".....kk..kk.....",
      ".....kwk.kwk....",
      "......kwkwk.....",
      ".......kwk......",
      ".......kkk......",
      "......kk.kk.....",
      "....kkk...kkk...",
      "...kRRk...kRRk..",
      "..kRkkRk.kRkkRk.",
      "..kRk.Rk.kRk.Rk.",
      "..kRkkRk.kRkkRk.",
      "...kRRk...kRRk..",
      "....kk.....kk...",
    ],
  },
  copy: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkk........",
      ".kwwwwwkk.......",
      ".kwwwwwkhk......",
      ".kwgggwkkk......",
      ".kwwwwkkkkkkk...",
      ".kwgggkwwwwwkk..",
      ".kwwwwkwwwwwkhk.",
      ".kwgggkwgggwkkk.",
      ".kwwwwkwwwwwwwk.",
      ".kkkkkkwggggwwk.",
      "......kwwwwwwwk.",
      "......kwggggwwk.",
      "......kwwwwwwwk.",
      "......kkkkkkkkk.",
      "................",
    ],
  },
  paste: {
    size: 16,
    rows: [
      "................",
      "....kkkk........",
      "...khhssk.......",
      "kkkksssgkkkk....",
      "kzzkkkkkkzzk....",
      "kzwwwwwwwwzk....",
      "kzwwwwwkkkkkkk..",
      "kzwwwwwkwwwwwkk.",
      "kzwwwwwkwwwwwkhk",
      "kzwwwwwkwgggwkkk",
      "kzwwwwwkwwwwwwwk",
      "kzwwwwwkwggggwwk",
      "kzwwwwwkwwwwwwwk",
      "kzwwwwwkwggggwwk",
      "kzzzzzzkwwwwwwwk",
      "kkkkkkkkkkkkkkkk",
    ],
  },
  undo: {
    size: 16,
    rows: [
      "................",
      "......p.........",
      ".....pqp........",
      "....pqqppp......",
      "...pqqqqqqpp....",
      "...pqqqqqqqqp...",
      "....pqqpppqqp...",
      ".....pqp..pqqp..",
      "......p...pqqp..",
      "..........pqqp..",
      "..........pqqp..",
      "....ppppppqqp...",
      "....pqqqqqqqp...",
      "....pqqqqqpp....",
      "....pppppp......",
      "................",
    ],
  },
  "expand-all": {
    size: 16,
    rows: [
      "................",
      "................",
      "..kkkkkkkkkkk...",
      "..kwwwwwwwwwk...",
      "..kwwwwkwwwsk...",
      "..kwwwwkwwwsk...",
      "..kwwwwkwwwsk...",
      "..kwkkkkkkksk...",
      "..kwwwwkwwwsk...",
      "..kwwwwkwwwsk...",
      "..kwwwwkwwwsk...",
      "..kwssssssssk...",
      "..kkkkkkkkkkk...",
      "................",
      "................",
      "................",
    ],
  },
  "collapse-all": {
    size: 16,
    rows: [
      "................",
      "................",
      "..kkkkkkkkkkk...",
      "..kwwwwwwwwwk...",
      "..kwwwwwwwwsk...",
      "..kwwwwwwwwsk...",
      "..kwwwwwwwwsk...",
      "..kwkkkkkkksk...",
      "..kwwwwwwwwsk...",
      "..kwwwwwwwwsk...",
      "..kwwwwwwwwsk...",
      "..kwssssssssk...",
      "..kkkkkkkkkkk...",
      "................",
      "................",
      "................",
    ],
  },
  "twistie-right": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "......k.........",
      "......kk........",
      "......ktk.......",
      "......kttk......",
      "......ktttk.....",
      "......kttk......",
      "......ktk.......",
      "......kk........",
      "......k.........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  "twistie-down": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "...kkkkkkkkk....",
      "....ktttttk.....",
      ".....ktttk......",
      "......ktk.......",
      ".......k........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },

  // mood stamps (shown in the memo header)
  "mood-personal": {
    size: 16,
    rows: [
      "................",
      "......kkkk......",
      ".....kwqqqk.....",
      "....kwqqqqpk....",
      "....kqqqqqpk....",
      "....kqqqqqpk....",
      "....kqqqqqpk....",
      ".....kqqppk.....",
      "....kkkkkkkk....",
      "...kwqqqqqqpk...",
      "..kwqqqqqqqqpk..",
      "..kqqqqqqqqqpk..",
      "..kqqqqqqqqqpk..",
      "..kqqqqqqqqqpk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  "mood-confidential": {
    size: 16,
    rows: [
      "................",
      "......kkkk......",
      ".....kzuuzk.....",
      ".....kzzzzk.....",
      "......kzzk......",
      "...kkkkkkkkkk...",
      "...kssssssssk...",
      "...kRRRRRRRRk...",
      "...kkkkkkkkkk...",
      "................",
      ".RRRRRRRRRRRRRR.",
      ".R............R.",
      ".R.RRRR.RRR.R.R.",
      ".R............R.",
      ".RRRRRRRRRRRRRR.",
      "................",
    ],
  },
  "mood-private": {
    size: 16,
    rows: [
      "................",
      "......kkkk......",
      ".....khssgk.....",
      "....kskkkkgk....",
      "....ksk..kgk....",
      "....ksk..kgk....",
      "..kkkkkkkkkkkk..",
      "..kYYYYYYYYYvk..",
      "..kYYYYkkYYYvk..",
      "..kYYYYkkYYYvk..",
      "..kYYYYkkYYYvk..",
      "..kYYYYYYYYYvk..",
      "..kYYYYYYYYYvk..",
      "..kvvvvvvvvvvk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  "mood-thankyou": {
    size: 16,
    rows: [
      "................",
      "................",
      "...kkk....kkk...",
      "..kRRRk..kRRRk..",
      ".kRwRRRkkRRRRRk.",
      ".kRRRRRRRRRRRrk.",
      ".kRRRRRRRRRRRrk.",
      "..kRRRRRRRRRrk..",
      "...kRRRRRRRrk...",
      "....kRRRRRrk....",
      ".....kRRRrk.....",
      "......kRrk......",
      ".......kk.......",
      "................",
      "................",
      "................",
    ],
  },
  "mood-flame": {
    size: 16,
    rows: [
      "................",
      ".......r........",
      "......rRr.......",
      "......rRRr......",
      ".....rRRRr......",
      ".....rRoRRr..r..",
      "....rRRooRr.rRr.",
      "...rRRooooRrRRr.",
      "..rRRooYYooRRRr.",
      "..rRooYYYYooRRr.",
      ".rRRoYYYYYYoRRr.",
      ".rRooYYwwYYooRr.",
      ".rRoYYwwwwYYoRr.",
      "..rRoYYwwYYoRr..",
      "...rrRRRRRRrr...",
      ".....rrrrrr.....",
    ],
  },
  "mood-goodjob": {
    size: 16,
    rows: [
      "................",
      "........k.......",
      ".......kYk......",
      ".......kYk......",
      "......kYYvk.....",
      "......kYYvk.....",
      ".kkkkkkYYvkkkkkk",
      "..kYYYYYYYYYYvk.",
      "...kYYYYYYYYvk..",
      "....kYYYYYYvk...",
      ".....kYYYYvk....",
      ".....kYYYYvk....",
      "....kYYYkYYvk...",
      "....kYYk.kYvk...",
      "...kYk.....kvk..",
      "...kk.......kk..",
    ],
  },
  "mood-joke": {
    size: 16,
    rows: [
      "................",
      ".....kkkkk......",
      "...kkYYYYYkk....",
      "..kYYYYYYYYYk...",
      "..kYYYYYYYYYk...",
      ".kYYYkYYYkYYYk..",
      ".kYYYkYYYkYYYk..",
      ".kYYYYYYYYYYvk..",
      ".kYkYYYYYYYkvk..",
      ".kYYkYYYYYkYvk..",
      "..kYYkkkkkYvk...",
      "..kYYYYYYYvvk...",
      "...kkYYvvvkk....",
      ".....kkkkk......",
      "................",
      "................",
    ],
  },
  "mood-fyi": {
    size: 16,
    rows: [
      "................",
      "..kkkkkkkk......",
      "..kwwwwwwkk.....",
      "..kwwwwbbkhk....",
      "..kwwwwbbkhhk...",
      "..kwwwwwwkkkkk..",
      "..kwwwbbbwwwwk..",
      "..kwwwwbbwwwwk..",
      "..kwwwwbbwwwwk..",
      "..kwwwwbbwwwwk..",
      "..kwwwwbbwwwwk..",
      "..kwwwwbbwwwwk..",
      "..kwwwbbbbwwwk..",
      "..kwwwwwwwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  "mood-question": {
    size: 16,
    rows: [
      "....nnnnnnn.....",
      "...nBBBBBBBn....",
      "..nBBaaaaBBBn...",
      "..nBBnnnnnBBBn..",
      "..nBBn...nBBBn..",
      "...nn...nBBBn...",
      ".......nBBBn....",
      "......nBBBn.....",
      "......nBBn......",
      "......nBBn......",
      ".......nn.......",
      "......nnnn......",
      ".....nBBBBn.....",
      ".....nBBBBn.....",
      "......nnnn......",
      "................",
    ],
  },
  "mood-reminder": {
    size: 16,
    rows: [
      "................",
      "....kk....kk....",
      "...kRRk..kRRk...",
      "...kRrRkkRrRk...",
      "....kkRRRRkk....",
      ".....kYYYvk.....",
      "....kYYYYYvk....",
      "....kYwYYYvk....",
      "....kYwYYYvk....",
      "....kYYYYYvk....",
      "...kYYYYYYYvk...",
      "..kYYYYYYYYYvk..",
      "..kkkkkkkkkkkk..",
      "......kkkk......",
      ".......kk.......",
      "................",
    ],
  },

  // Notes 8 sidebar
  activities: {
    size: 16,
    rows: [
      "................",
      ".....kkkk.......",
      "....khhssk......",
      ".kkkksssgkkkk...",
      ".kzzkkkkkkzzk...",
      ".kzwkkkwwwwzk...",
      ".kzwkGkwgggzk...",
      ".kzwkkkwwwwzk...",
      ".kzwwwwwwwwzk...",
      ".kzwkkkwwwwzk...",
      ".kzwkGkwgggzk...",
      ".kzwkkkwwwwzk...",
      ".kzwwwwwwwwzk...",
      ".kzwgggggggzk...",
      ".kzzzzzzzzzzk...",
      ".kkkkkkkkkkkk...",
    ],
  },
  feeds: {
    size: 16,
    rows: [
      "................",
      "..zzzzzzzzzzzz..",
      ".zooooooooooooo.",
      ".zowwwwwooooooo.",
      ".zooooowwoooooz.",
      ".zoooooooowoooz.",
      ".zowwwooooowooz.",
      ".zoooowwoooowoz.",
      ".zooooowooooowz.",
      ".zoooooowoooowz.",
      ".zowwoooowoooow.",
      ".zowwoooowoooow.",
      ".zooooooooooooz.",
      ".zooooooooooooz.",
      "..zzzzzzzzzzzz..",
      "................",
    ],
  },
  quickr: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      ".kkkkk..........",
      "kYYYYYk.........",
      "kYYYYYYkkkkkkkk.",
      "kYYYYYYnnnnnYYk.",
      "kYYYYYnnYYYnnvk.",
      "kYYYYYnnYYYnnvk.",
      "kYYYYYnnYYYnnvk.",
      "kYYYYYnnYnYnnvk.",
      "kYYYYYnnYYnnnvk.",
      "kYYYYYYnnnnnYvk.",
      "kvvvvvvvvvvnnvk.",
      "kkkkkkkkkkkkkkk.",
      "................",
    ],
  },
  sidekick: {
    size: 16,
    rows: [
      "................",
      "................",
      "kkkkkk....kkkkkk",
      "kllllkkkkkkaaaak",
      "kllllkGGGGkaaaak",
      "kRlllkGGGGkaaaak",
      "klRllkGGGGkalaak",
      "kllRlkRGGGkallak",
      "kalllkGRBBkaRlak",
      "kaallkBBRBkRllak",
      "kaaalkBBBRkaaaak",
      "kaaalkBBBBkaaaak",
      "kaaaakBBBBkaaaak",
      "kkkkkkBBBBkkkkkk",
      ".....kkkkkk.....",
      "................",
    ],
  },
  "day-glance": {
    size: 16,
    rows: [
      "................",
      "..kk.......kk...",
      "..kk.......kk...",
      "kkkkkkkkkkkkkkk.",
      "kRkkRRRRRRRkkRk.",
      "kRRRRRRRRRRRRRk.",
      "krrrrrrrrrrrrrk.",
      "kwwwwwwwwkkkkkk.",
      "kwwwwwwwkwwkwwk.",
      "kwwwwwwkwwwkwwwk",
      "kwwwwwwkwwwkwwwk",
      "kwwwwwwkwwwkkkwk",
      "kwwwwwwkwwwwwwsk",
      "kwwwwwwkwwwwwwsk",
      "kkkkkkkkkwwwwsk.",
      ".........kkkkk..",
    ],
  },
};
