// ============================================================================
// 16x16 pixel icons, group A: applications, chrome, mail, status bar.
// Names and intended subjects are listed in names.ts (ICON16A_NAMES).
//
// Original artwork in the spirit of Windows 95 / Notes R4-R5 SmartIcons:
// 1px dark outline, light from the top-left, flat PALETTE colors, a clear
// 1px margin. Shared motifs (envelope, sheet, calendar page, manila folder,
// tray, "new" sparkle, arrows) are drawn identically wherever they recur.
// Only "follow-up" uses the "@" tint slot (its flag cloth).
// ============================================================================

import type { Icon16AName } from "./names";
import type { PixelIcon } from "./types";

export const ICONS16A: Record<Icon16AName, PixelIcon> = {
  home: {
    size: 16,
    rows: [
      "................",
      ".......kk.kkkk..",
      "......kRRkkzzk..",
      ".....kRRRRkzzk..",
      "....kRRRRRRkzk..",
      "...kRRRRRRRRkk..",
      "..kRRRRRRRRRRk..",
      ".kkkkkkkkkkkkkk.",
      "...kwwwwwwwwk...",
      "...kBBwwwwBBk...",
      "...kBBwzzwBBk...",
      "...kwwwzzwwwk...",
      "...kwwwzzwwwk...",
      "...kwwwzzwwwk...",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  workspace: {
    size: 16,
    rows: [
      "................",
      ".kkkkkk..kkkkkk.",
      ".kaaabk..kiiirk.",
      ".kaBBbk..kiRRrk.",
      ".kaBBbk..kiRRrk.",
      ".kbbbbk..krrrrk.",
      ".kkkkkk..kkkkkk.",
      "................",
      "................",
      ".kkkkkk..kkkkkk.",
      ".klllek..kwwwvk.",
      ".klGGek..kwYYvk.",
      ".klGGek..kwYYvk.",
      ".keeeek..kvvvvk.",
      ".kkkkkk..kkkkkk.",
      "................",
    ],
  },
  mail: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kdwwwwwwwwwwdk.",
      ".kwdwwwwwwwwdwk.",
      ".kwwdwwwwwwdwwk.",
      ".kwwwdwwwwdwwwk.",
      ".kwwwwdwwdwwwwk.",
      ".kwwwwwddwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kggggggggggggk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
      "................",
    ],
  },
  calendar: {
    size: 16,
    rows: [
      "................",
      "...kk......kk...",
      ".kkkkkkkkkkkkkk.",
      ".kRkkRRRRRRkkRk.",
      ".kRRRRRRRRRRRRk.",
      ".krrrrrrrrrrrrk.",
      ".kwswwswwswwswk.",
      ".kwswwswwswwswk.",
      ".kssssssssssssk.",
      ".kwswwswwswwswk.",
      ".kwswwswwswwswk.",
      ".kssssssssssssk.",
      ".kwswwswwswwswk.",
      ".kwswwswwswwswk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  addressbook: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkkkkkk...",
      ".kzzzzzzzzzzkkk.",
      ".kzkkkkkkkkzkRk.",
      ".kzkwwwwwwkzkRk.",
      ".kzkwwuuwwkzkkk.",
      ".kzkwwuuwwkzkYk.",
      ".kzkwBBBBwkzkYk.",
      ".kzkwBBBBwkzkkk.",
      ".kzkkkkkkkkzkGk.",
      ".kzzzzzzzzzzkGk.",
      ".kzzzzzzzzzzkkk.",
      ".kwwwwwwwwwwk...",
      ".kkkkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  todo: {
    size: 16,
    rows: [
      "................",
      "......kkkk......",
      ".kkkkkssssskkkk.",
      ".kzzzkggggkzzzk.",
      ".kzwwkkkkkkwwzk.",
      ".kzwwwwwwwwwwzk.",
      ".kzwwwwewwwwwzk.",
      ".kzwewewggggwzk.",
      ".kzwwewwwwwwwzk.",
      ".kzwwwwwwwwwwzk.",
      ".kzwwwwewwwwwzk.",
      ".kzwewewggggwzk.",
      ".kzwwewwwwwwwzk.",
      ".kzzzzzzzzzzzzk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  notebook: {
    size: 16,
    rows: [
      "................",
      "...kkkkkkkkkkk..",
      ".kskttttttttttk.",
      "...kttttttttttk.",
      ".ksktwwwwwwwttk.",
      "...ktwggggwwttk.",
      ".ksktwwwwwwwttk.",
      "...kttttttttttk.",
      ".kskttttttttttk.",
      "...kttttttttttk.",
      ".kskttttttttttk.",
      "...kttttttttttk.",
      ".kskttttttttttk.",
      "...kttttttttttk.",
      "...kkkkkkkkkkkk.",
      "................",
    ],
  },
  discussion: {
    size: 16,
    rows: [
      "................",
      "................",
      "..kkkkkkkk......",
      ".kaaaaaaaak.....",
      ".kaaaaaaaak.....",
      ".kaaaaaaaak.....",
      ".kaaaakkkkkkkk..",
      "..kkakwwwwwwwwk.",
      "..kakkwwwwwwwwk.",
      "..kk.kwwwwwwwwk.",
      ".....kwwwwwwwwk.",
      ".....kwwwwwwwwk.",
      "......kkkkwwkk..",
      "..........kwk...",
      "...........kk...",
      "................",
    ],
  },
  search: {
    size: 16,
    rows: [
      "................",
      "....kkkk........",
      "..kkaaaakk......",
      "..kwwaaaak......",
      ".kawaaaaaak.....",
      ".kawaaaaaak.....",
      ".kaaaaaaaak.....",
      ".kaaaaaaaak.....",
      "..kaaaaaak......",
      "..kkaaaakkk.....",
      "....kkkkkzzk....",
      ".........kzzk...",
      "..........kzzk..",
      "...........kzzk.",
      "............kk..",
      "................",
    ],
  },
  replicator: {
    size: 16,
    rows: [
      "................",
      "................",
      ".....nnnnnn.....",
      "....nBBBBBBn....",
      "...nBBnnnnBBn...",
      "...nnn....nBBn..",
      "..........nnBnn.",
      "..eGe.....nBBBn.",
      ".eGGGe.....nBn..",
      ".eeGee..........",
      "..eGGe....eee...",
      "...eGGeeeeGGe...",
      "....eGGGGGGe....",
      ".....eeeeee.....",
      "................",
      "................",
    ],
  },
  help: {
    size: 16,
    rows: [
      "................",
      "...kkkkkkkkkkk..",
      "..knBBBBBBBBBk..",
      "..knBBYYYYBBBk..",
      "..knBYYBBYYBBk..",
      "..knBYYBBYYBBk..",
      "..knBBBBBYYBBk..",
      "..knBBBBYYBBBk..",
      "..knBBBYYBBBBk..",
      "..knBBBYYBBBBk..",
      "..knBBBBBBBBBk..",
      "..knBBBYYBBBBk..",
      "..knkkkkkkkkkk..",
      "..knwwwwwwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  directory: {
    size: 16,
    rows: [
      "................",
      "...kkkkkkkkkkk..",
      "..knBBBBBBBBBk..",
      "..knBBBkkkBBBk..",
      "..knBBkcGckBBk..",
      "..knBkGGGcckBk..",
      "..knBkcGccGkBk..",
      "..knBkccGGGkBk..",
      "..knBBkcGckBBk..",
      "..knBBBkkkBBBk..",
      "..knBBBBBBBBBk..",
      "..knBBBBBBBBBk..",
      "..knkkkkkkkkkk..",
      "..knwwwwwwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  outbox: {
    size: 16,
    rows: [
      "................",
      "................",
      "...kkkkkkkkkk...",
      "...kdwwwwwwdk...",
      "...kwdwwwwdwk...",
      ".k.kwwdwwdwwk.k.",
      ".kkkwwwddwwwkkk.",
      ".kfkwwwwwwwwkzk.",
      ".kkkkkkkkkkkkkk.",
      ".kfuuuuuuuuuuzk.",
      "..kfuuuuuuuuzk..",
      "..kuuuuuuuuuuk..",
      "...kzzzzzzzzk...",
      "...kkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  database: {
    size: 16,
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkhhhhhhkk...",
      "..khhhhhhhhhhk..",
      "..kkkhhhhhhkkk..",
      "..kwskkkkkksgk..",
      "..kwsssssssggk..",
      "..kwsssssssggk..",
      "..kwsssssssggk..",
      "..kwsssssssggk..",
      "..kwsssssssggk..",
      "..kwsssssssggk..",
      "..kwsssssssggk..",
      "...kkssssggkk...",
      ".....kkkkkk.....",
      "................",
    ],
  },
  back: {
    size: 16,
    rows: [
      "................",
      "................",
      "......ee........",
      ".....ele........",
      "....elGe........",
      "...elGGeeeeeeee.",
      "..elGGGllllllle.",
      ".elGGGGGGGGGGGe.",
      ".eGGGGGGGGGGGGe.",
      "..eGGGGGGGGGGGe.",
      "...eGGGeeeeeeee.",
      "....eGGe........",
      ".....eGe........",
      "......ee........",
      "................",
      "................",
    ],
  },
  forward: {
    size: 16,
    rows: [
      "................",
      "................",
      "........ee......",
      "........ele.....",
      "........eGle....",
      ".eeeeeeeeGGle...",
      ".elllllllGGGle..",
      ".eGGGGGGGGGGGle.",
      ".eGGGGGGGGGGGGe.",
      ".eGGGGGGGGGGGe..",
      ".eeeeeeeeGGGe...",
      "........eGGe....",
      "........eGe.....",
      "........ee......",
      "................",
      "................",
    ],
  },
  stop: {
    size: 16,
    rows: [
      "................",
      ".....kkkkkk.....",
      "....kiiiRRRk....",
      "...kiRRRRRRRk...",
      "..kiRRRRRRRRRk..",
      ".kiRRRRRRRRRRRk.",
      ".kiRRRRRRRRRRRk.",
      ".kRRwwwwwwwwRrk.",
      ".kRRwwwwwwwwRrk.",
      ".kRRRRRRRRRRRrk.",
      ".kRRRRRRRRRRRrk.",
      "..kRRRRRRRRRrk..",
      "...kRRRRRRRrk...",
      "....krrrrrrk....",
      ".....kkkkkk.....",
      "................",
    ],
  },
  refresh: {
    size: 16,
    rows: [
      "................",
      "................",
      ".....eeeeee.....",
      "....eGGGGGGe....",
      "...eGGeeeeGGe...",
      "...eee....eGGe..",
      "..........eeGee.",
      "..eGe.....eGGGe.",
      ".eGGGe.....eGe..",
      ".eeGee..........",
      "..eGGe....eee...",
      "...eGGeeeeGGe...",
      "....eGGGGGGe....",
      ".....eeeeee.....",
      "................",
      "................",
    ],
  },
  favorites: {
    size: 16,
    rows: [
      "................",
      ".......kk.......",
      "......kwYk......",
      "......kYvk......",
      ".....kYYYvk.....",
      ".kkkkkYYYYkkkkk.",
      ".kwYYYYYYYYYYvk.",
      "..kYYYYYYYYYvk..",
      "...kYYYYYYYvk...",
      "....kYYYYYvk....",
      "....kYYYYYvk....",
      "...kYYYkkYYvk...",
      "...kYYk..kYvk...",
      "..kYkk....kkvk..",
      "..kk........kk..",
      "................",
    ],
  },
  "bookmark-folder": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "..kkkkk.........",
      ".kwwwwwk........",
      ".kwYYYYYkkkkkkk.",
      ".kwYYYYYwwwwwvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYkYvk.",
      ".kwYYYYYYYkYkvk.",
      ".kwYYYYYkkkYkkk.",
      ".kwYYYYYkYYYYYk.",
      ".kvvvvvvvkYYYkk.",
      ".kkkkkkkkkYkYkk.",
      ".........kk.kk..",
      "................",
    ],
  },
  history: {
    size: 16,
    rows: [
      "................",
      ".....kkkkk......",
      "...kkwwgwwkk....",
      "..kwwwwkwwwwk...",
      "..kwwwwkwwwwk...",
      ".kwwwwwkwwwwwk..",
      ".kwwwwwkwwwwwk..",
      ".kgwwwwRkkkwgk..",
      ".kwwwwwwwwwwwk..",
      ".kwwwwwwwwwwhk..",
      "..kwwwwwwwwhk...",
      "..kwwwwwwwhhk...",
      "...kkhhghhkk....",
      ".....kkkkk......",
      "................",
      "................",
    ],
  },
  print: {
    size: 16,
    rows: [
      "................",
      "................",
      "....kkkkkkkk....",
      "....kwwwwwwk....",
      "....kwggggwk....",
      "....kwwwwwwk....",
      "..kkkwggggwkkk..",
      ".khhhhhhhhhhhhk.",
      ".kkkkkkkkkkkkkk.",
      ".kwssssssssssgk.",
      ".kwsssssssGGsgk.",
      ".kwkkkkkkkkkkgk.",
      ".kggggggggggggk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  open: {
    size: 16,
    rows: [
      "................",
      "...........e....",
      "..........eGe...",
      ".........eGGGe..",
      ".........eeGee..",
      "..........eGe...",
      "..kkkk....eGe...",
      ".kvvvvkkkkeGek..",
      ".kvvvvvvvveGek..",
      ".kvvkkkkkkkkkkk.",
      ".kvkYYYYYYYYYk..",
      ".kkYYYYYYYYYk...",
      ".kYYYYYYYYYk....",
      ".kkkkkkkkkk.....",
      "................",
      "................",
    ],
  },
  "new-database": {
    size: 16,
    rows: [
      "................",
      "...........Y....",
      "...........Y....",
      "....kkkkk.YoY...",
      "..kkhhhhYYoooYY.",
      ".khhhhhhhhYoY...",
      ".kkkhhhhhkkY....",
      ".kwskkkkksgY....",
      ".kwssssssggk....",
      ".kwssssssggk....",
      ".kwssssssggk....",
      ".kwssssssggk....",
      ".kwssssssggk....",
      "..kksssggkk.....",
      "....kkkkk.......",
      "................",
    ],
  },
  "new-memo": {
    size: 16,
    rows: [
      "................",
      "...........Y....",
      ".kkkkkkk...Y....",
      ".kwwwwwkk.YoY...",
      ".kwwwwwkYYoooYY.",
      ".kwggggkhhYoY...",
      ".kwwwwwkkkkY....",
      ".kwgggggggwY....",
      ".kwwwwwwwwwk....",
      ".kwgggggggwk....",
      ".kwwwwwwwwwk....",
      ".kwgggggggwk....",
      ".kwwwwwwwwwk....",
      ".kwggggwwwwk....",
      ".kkkkkkkkkkk....",
      "................",
    ],
  },
  reply: {
    size: 16,
    rows: [
      "................",
      ".....pp.........",
      "....pqp.........",
      "...pqqp.........",
      "..pqqqpppppp....",
      ".pqqqqqqqqqqp...",
      ".pqqqqqqqqqqqp..",
      "..pqqqpppppqqp..",
      "...pqqp...pqqp..",
      "....pqp...pqqp..",
      ".....pp...pqqp..",
      "..........pqqp..",
      "..........pqqp..",
      "..........pppp..",
      "................",
      "................",
    ],
  },
  "reply-all": {
    size: 16,
    rows: [
      "................",
      ".....pp..pp.....",
      "....pqp.pqp.....",
      "...pqqppqqp.....",
      "..pqqqpqqqpp....",
      ".pqqqqqqqqqqp...",
      ".pqqqqqqqqqqqp..",
      "..pqqqpqqqpqqp..",
      "...pqqppqqpqqp..",
      "....pqp.pqpqqp..",
      ".....pp..ppqqp..",
      "..........pqqp..",
      "..........pqqp..",
      "..........pppp..",
      "................",
      "................",
    ],
  },
  "forward-mail": {
    size: 16,
    rows: [
      "................",
      ".kkkkkk.........",
      ".kwwwwkk........",
      ".kwwwwkhk.......",
      ".kwgggkkkk......",
      ".kwwwwwwwk......",
      ".kwgggggwkb.....",
      ".kwwwwwwwkbb....",
      ".kwggbbbbbbBb...",
      ".kwwwbBBBBBBBb..",
      ".kwggbBBBBBBBBb.",
      ".kwwwbBBBBBBBb..",
      ".kkkkbbbbbbBb...",
      "..........bb....",
      "..........b.....",
      "................",
    ],
  },
  "follow-up": {
    size: 16,
    rows: [
      "................",
      "..kk............",
      "..hkkkkkk.......",
      "..hk@@@@@kkkkk..",
      "..hk@@@@@@@@@k..",
      "..hk@@@@@@@@@k..",
      "..hk@@@@@@@@@k..",
      "..hk@@@@@@@@@k..",
      "..hkkkkk@@@@@k..",
      "..hk....kkkkkk..",
      "..hk............",
      "..hk............",
      "..hk............",
      "..hk............",
      ".kkkk...........",
      "................",
    ],
  },
  "mark-read": {
    size: 16,
    rows: [
      "................",
      "................",
      ".......kk.......",
      "......khhk......",
      ".....khhhhk.....",
      "....khhhhhhk....",
      "...khhhhhhhhk...",
      "..khhhhhhhhhhk..",
      ".kkkkkkkkkkkkkk.",
      ".kddssssssssddk.",
      ".kwwddssssddwwk.",
      ".kwwwwddddwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kggggggggggggk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "mark-unread": {
    size: 16,
    rows: [
      "................",
      "...........R....",
      "..........RRR...",
      "........RRRRRRR.",
      ".........RRRRR..",
      "..........RRR...",
      ".kkkkkkkkRRkRR..",
      ".kdwwwwwwRwdk.R.",
      ".kwdwwwwwwdwk...",
      ".kwwdwwwwdwwk...",
      ".kwwwdwwdwwwk...",
      ".kwwwwddwwwwk...",
      ".kwwwwwwwwwwk...",
      ".kggggggggggk...",
      ".kkkkkkkkkkkk...",
      "................",
    ],
  },
  trash: {
    size: 16,
    rows: [
      "................",
      "......kkkk......",
      "......k..k......",
      ".kkkkkkkkkkkkkk.",
      ".khhhhhhhhhhhhk.",
      ".kkkkkkkkkkkkkk.",
      "..kwsgssgssggk..",
      "..kwsgssgssggk..",
      "..kwsgssgssggk..",
      "..kwsgssgssggk..",
      "..kwsgssgssggk..",
      "..kwsgssgssggk..",
      "..kwsgssgssggk..",
      "..kwsgssgssggk..",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  "copy-into": {
    size: 16,
    rows: [
      "................",
      ".kkkkkk.........",
      ".kwwwwkk........",
      ".kwwwwkhk.......",
      ".kwgggkkk.......",
      ".kwwwwkkkkkk....",
      ".kwgggkwwwwkk...",
      ".kwwwwkwwwwkhk..",
      ".kwgggkwgggkkk..",
      ".kkkkkkwwwwwwk..",
      "...e..kwggggwk..",
      ".eeGe.kwwwwwwk..",
      ".eGGGekwggggwk..",
      ".eeGe.kwwwwwwk..",
      "...e..kkkkkkkk..",
      "................",
    ],
  },
  folder: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "..kkkkk.........",
      ".kwwwwwk........",
      ".kwYYYYYkkkkkkk.",
      ".kwYYYYYwwwwwvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kvvvvvvvvvvvvk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  "folder-open": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "..kkkk..........",
      ".kvvvvkkkkkkk...",
      ".kvvvvvvvvvvvk..",
      ".kvvvvvvvvvvvk..",
      ".kvvvkkkkkkkkkk.",
      ".kvvkYYYYYYYYk..",
      ".kvkYYYYYYYYk...",
      ".kkYYYYYYYYk....",
      ".kYYYYYYYYk.....",
      ".kkkkkkkkkk.....",
      "................",
      "................",
    ],
  },
  "move-to-folder": {
    size: 16,
    rows: [
      "................",
      "..........eee...",
      "..........eGe...",
      "..........eGe...",
      "..kkkkk.eeeGeee.",
      ".kwwwwwk.eGGGe..",
      ".kwYYYYYkkeGekk.",
      ".kwYYYYYwwwewvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kvvvvvvvvvvvvk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  rules: {
    size: 16,
    rows: [
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      ".kwaaaaaaaaaaBk.",
      ".kkkkkkkkkkkkkk.",
      "..kaBBBBBBBBnk..",
      "...kaBBBBBBnk...",
      "....kaBBBBnk....",
      ".....kaBBnk.....",
      "......kaBk......",
      "......kaBk......",
      "......kaBk......",
      "......kaBk......",
      "......kkkk......",
      "................",
      "................",
    ],
  },
  inbox: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "...kkkkkkkkkk...",
      "...kwwwwwwwwk...",
      "...kwggggggwk...",
      ".k.kwwwwwwwwk.k.",
      ".kkkwggggggwkkk.",
      ".kfkwwwwwwwwkzk.",
      ".kkkkkkkkkkkkkk.",
      ".kfuuuuuuuuuuzk.",
      "..kfuuuuuuuuzk..",
      "..kuuuuuuuuuuk..",
      "...kzzzzzzzzk...",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  drafts: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkk.......",
      ".kwwwwwwkk......",
      ".kwwwwwwkhk.....",
      ".kwggggwkhhkkk..",
      ".kwwwwwwkkkkiik.",
      ".kwgggggggkssk..",
      ".kwwwwwwwkYvk...",
      ".kwgggggkYvkk...",
      ".kwwwwwkYvkwk...",
      ".kwgggkYvkgwk...",
      ".kwwwkuukwwwk...",
      ".kwgkukgwwwwk...",
      ".kwwkwwwwwwwk...",
      ".kkkkkkkkkkkk...",
      "................",
    ],
  },
  sent: {
    size: 16,
    rows: [
      "................",
      ".......ee.......",
      "......eGGe......",
      ".....eGGGGe.....",
      "....eGGGGGGe....",
      "....eeeGGeee....",
      ".k....eGGe....k.",
      ".kk...eGGe...kk.",
      ".kf...eGGe...zk.",
      ".kkkkkkkkkkkkkk.",
      ".kfuuuuuuuuuuzk.",
      "..kfuuuuuuuuzk..",
      "..kuuuuuuuuuuk..",
      "...kzzzzzzzzk...",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  "all-documents": {
    size: 16,
    rows: [
      "................",
      ".....kkkkkkkkkk.",
      ".....kwwwwwwwwk.",
      "...kkkkkkkkkkwk.",
      "...kwwwwwwwwkwk.",
      ".kkkkkkkkkkwkwk.",
      ".kwwwwwwwwkwkwk.",
      ".kwggggggwkwkwk.",
      ".kwwwwwwwwkwkwk.",
      ".kwggggggwkwkwk.",
      ".kwwwwwwwwkwkkk.",
      ".kwggggggwkwk...",
      ".kwwwwwwwwkkk...",
      ".kwggggwwwk.....",
      ".kkkkkkkkkk.....",
      "................",
    ],
  },
  junk: {
    size: 16,
    rows: [
      "................",
      ".....RRRRRR.....",
      "....RRRRRRRR....",
      ".kkRRRkkkkRRRkk.",
      ".kRRRRwwwwwwRrk.",
      ".RRRwRRwwwwwRrr.",
      ".RRwdwRRwwwdwRr.",
      ".RRwwdwRRwdwwRr.",
      ".RRwwwdwRRwwwRr.",
      ".RRwwwwddRRwwRr.",
      ".RRRwwwwwwRRRrr.",
      ".kRRgggggggRRrk.",
      ".kkRRRkkkkRRrkk.",
      "....rrRRRRrr....",
      ".....rrrrrr.....",
      "................",
    ],
  },
  "chat-history": {
    size: 16,
    rows: [
      "................",
      "..kkkkkkkkkk....",
      ".kwwwwwwwwwwk...",
      ".kwwwwwwwwwwk...",
      ".kwwwwwwwwwwk...",
      ".kwwwwwwwwwwk...",
      ".kwwwwwwwwwwk...",
      ".kwwwwwwwwkkk...",
      "..kkwkkkkkYYYk..",
      "...kwk..kYYkYYk.",
      "...kk...kYYkkYk.",
      "........kYYYYYk.",
      ".........kYYYk..",
      "..........kkk...",
      "................",
      "................",
    ],
  },
  view: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".knnnnnnnnnnnnk.",
      ".kkkkkkkkkkkkkk.",
      ".ksssksssssssgk.",
      ".kkkkkkkkkkkkkk.",
      ".kwggkwgggggwwk.",
      ".kaaakaaaaaaaak.",
      ".kwggkwggggwwwk.",
      ".kaaakaaaaaaaak.",
      ".kwggkwgggggggk.",
      ".kaaakaaaaaaaak.",
      ".kwggkwggggwwwk.",
      ".kwwwkwwwwwwwwk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  archive: {
    size: 16,
    rows: [
      "................",
      "..kkkkkkkkkkkk..",
      "..khhhhhhhhhgk..",
      "..khsskkkkssgk..",
      "..khsssssssggk..",
      "..kkkkkkkkkkkk..",
      "..khhhhhhhhhgk..",
      "..khsskkkkssgk..",
      "..khsssssssggk..",
      "..kkkkkkkkkkkk..",
      "..khhhhhhhhhgk..",
      "..khsskkkkssgk..",
      "..khsssssssggk..",
      "..kggggggggggk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  tools: {
    size: 16,
    rows: [
      "................",
      "................",
      "........kkk.....",
      ".......khhsk....",
      ".......khsk.....",
      ".......khk..kk..",
      ".......khk.kssk.",
      "......khsskhssk.",
      ".....khsssssssk.",
      "....khssssskkk..",
      "...khssskkk.....",
      "..khsssk........",
      ".khsssk.........",
      ".kssk...........",
      "..kk............",
      "................",
    ],
  },
  "other-mail": {
    size: 16,
    rows: [
      "................",
      "................",
      "...kkkkkkkkkkkk.",
      "...kdwwwwwwwwdk.",
      "...kwdwwwwwwdwk.",
      "...kwwdwwwwdwwk.",
      ".kkkkkkkkkkkkwk.",
      ".kdwwwwwwwwdkwk.",
      ".kwdwwwwwwdwkgk.",
      ".kwwdwwwwdwwkkk.",
      ".kwwwdwwdwwwk...",
      ".kwwwwddwwwwk...",
      ".kggggggggggk...",
      ".kkkkkkkkkkkk...",
      "................",
      "................",
    ],
  },
  meetings: {
    size: 16,
    rows: [
      "................",
      "...kk......kk...",
      ".kkkkkkkkkkkkkk.",
      ".kRkkRRRRRRkkRk.",
      ".kRRRRRRRRRRRRk.",
      ".krrrrrrrrrrrrk.",
      ".kwzzzwwwwzzzwk.",
      ".kzzzzzwwzzzzzk.",
      ".kzuuuzwwzuuuzk.",
      ".kzuuuzwwzuuuzk.",
      ".kwzzzwwwwzzzwk.",
      ".kwBBBwwwwBBBwk.",
      ".kBBBBBwwBBBBBk.",
      ".kBBBBBwwBBBBBk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  attachment: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      ".......ddd......",
      "......dsssd.....",
      "......sd.ds.....",
      ".....dsdsds.....",
      ".....dsdsds.....",
      ".....dsdsds.....",
      ".....dsdsd......",
      ".....ds.sd......",
      "......dssd......",
      ".......dd.......",
      "................",
      "................",
      "................",
    ],
  },
  importance: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "......RRr.......",
      "......RRr.......",
      "......RRr.......",
      "......RRr.......",
      "......RRr.......",
      ".......Rr.......",
      ".......Rr.......",
      "................",
      "......RRr.......",
      "......RRr.......",
      "................",
      "................",
      "................",
    ],
  },
  "unread-star": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      ".......R........",
      ".......R........",
      "......RRR.......",
      "...RRRRRRRRR....",
      "....RRRRRRR.....",
      ".....RRRRR......",
      "....RRRRRRR.....",
      "....RRR.RRR.....",
      "...RR.....RR....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  check: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "...........ee...",
      "..........eGe...",
      ".........eGGe...",
      "....e...eGGe....",
      "...eGe.eGGe.....",
      "...eGGeGGe......",
      "....eGGGe.......",
      ".....eGe........",
      "......e.........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  replied: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "......p.........",
      ".....pqp........",
      "....pqqpppp.....",
      "...pqqqqqqqp....",
      "....pqqppqqp....",
      ".....pqp.pqp....",
      "......p..pqp....",
      ".........ppp....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  forwarded: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "........bb......",
      "........bBb.....",
      "...bbbbbbBBb....",
      "...bBBBBBBBBb...",
      "...bBBBBBBBBb...",
      "...bbbbbbBBb....",
      "........bBb.....",
      "........bb......",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  conflict: {
    size: 16,
    rows: [
      "................",
      ".......kk.......",
      "......kYYk......",
      ".....kYYYYk.....",
      "....kYYkkYYk....",
      "...kYYYkkYYYk...",
      "..kYYYYkkYYYYk..",
      ".kYYYYYkkYYYYYk.",
      ".kYYYYYkkYYYYvk.",
      "..kYYYYYYYYYvk..",
      "...kYYYkkYYvk...",
      "....kYYkkYvk....",
      ".....kYYYvk.....",
      "......kYvk......",
      ".......kk.......",
      "................",
    ],
  },
  response: {
    size: 16,
    rows: [
      "................",
      "................",
      "......kkkkkk....",
      "......kwwwwkk...",
      "......kwwwwkhk..",
      "......kwgggkkkk.",
      ".eee..kwwwwwwwk.",
      ".eGe..kwgggggwk.",
      ".eGe..kwwwwwwwk.",
      ".eGe.eegggggwwk.",
      ".eGeeeGewwwwwwk.",
      ".eGGGGGGegggwwk.",
      ".eeeeeGewwwwwwk.",
      ".....eekkkkkkkk.",
      "................",
      "................",
    ],
  },
  send: {
    size: 16,
    rows: [
      "................",
      "................",
      ".kkkkkkkkkkkk...",
      ".kdwwwwwwwwdk...",
      ".kwdwwwwwwdwk...",
      ".kwwdwwwwdwwk...",
      ".kwwwdwwdwwwk...",
      ".kwwwwddwweek...",
      ".kwwwwwwwweGe...",
      ".kgggeeeeeeGGe..",
      ".kkkkeGGGGGGGGe.",
      ".....eGGGGGGGGe.",
      ".....eeeeeeGGe..",
      "..........eGe...",
      "..........ee....",
      "................",
    ],
  },
  "send-file": {
    size: 16,
    rows: [
      "................",
      "................",
      ".kkkkkkkkkkkk...",
      ".kdwwwwwwwwdk...",
      ".kwdwwwwwwdwk...",
      ".kwwdwwwwdwwk...",
      ".kwwwdwwdwwwk...",
      ".kwwwwddwwwwk...",
      ".kggggggkkkgk...",
      ".kkkkkkkwwwkkkk.",
      ".......kwYYYYYk.",
      ".......kwYYYYYk.",
      ".......kwYYYYYk.",
      ".......kvvvvvvk.",
      ".......kkkkkkkk.",
      "................",
    ],
  },
  save: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkkkkkkk..",
      ".kBkssssddskBbk.",
      ".kBkssssddskBbk.",
      ".kBkssssddskBbk.",
      ".kBkkkkkkkkkBbk.",
      ".kBBBBBBBBBBBbk.",
      ".kBkkkkkkkkkkbk.",
      ".kBkwwwwwwwwkbk.",
      ".kBkwggggggwkbk.",
      ".kBkwwwwwwwwkbk.",
      ".kBkwggggggwkbk.",
      ".kBkwwwwwwwwkbk.",
      ".kBkwwwwwwwwkbk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  "delivery-options": {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkkkkkk...",
      ".kdwwwwwwwwdk...",
      ".kwdwwwwwwdwk...",
      ".kwwdwwwwdwwk...",
      ".kwwwdwwdwwwk...",
      ".kwwwwddwkkkk...",
      ".kgggggkkkhkkk..",
      ".kkkkkkkkhhsskk.",
      "......kkhhsssgk.",
      "......khhskksgk.",
      "......khsskksgk.",
      "......kkssssggk.",
      ".......kksgggkk.",
      ".......kk.kkk.k.",
      "................",
    ],
  },
  address: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkk.......",
      ".kzzzzzzkkk.....",
      ".kzkkkkzkRk.....",
      ".kzkwwkzkRk.....",
      ".kzkuukzkkk.....",
      ".kzkBBkzkYk.....",
      ".kzkkkkzkYk.....",
      ".kzzzzzzkkke....",
      ".kzzzzzzkGkee...",
      ".kzzzzzeeeeeGe..",
      ".kzzzzzeGGGGGGe.",
      ".kwwwwweeeeeGe..",
      ".kkkkkkkk..ee...",
      "...........e....",
      "................",
    ],
  },
  discard: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "..RRr.......RRr.",
      "...RRr.....RRr..",
      "....RRr...RRr...",
      ".....RRr.RRr....",
      "......RRRRr.....",
      ".......RRr......",
      "......RRRRr.....",
      ".....RRr.RRr....",
      "....RRr...RRr...",
      "...RRr.....RRr..",
      "..RRr.......RRr.",
      "................",
      "................",
    ],
  },
  attach: {
    size: 16,
    rows: [
      "................",
      ".....ddd........",
      "....dsssd.......",
      "....sd.ds.......",
      "..kdsdsdsk......",
      "..kdsdsdskk.....",
      "..kdsdsdskhk....",
      "..kdsdsdwkhhk...",
      "..kdswsdwkkkkk..",
      "..kwdssdggggwk..",
      "..kwwddwwwwwwk..",
      "..kwggggggggwk..",
      "..kwwwwwwwwwwk..",
      "..kwgggggwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  edit: {
    size: 16,
    rows: [
      "................",
      "............kk..",
      "...........kiik.",
      "..........kiik..",
      ".........khgk...",
      "........kYvk....",
      ".......kYvk.....",
      "......kYvk......",
      ".....kYvk.......",
      "....kYvk........",
      "...kuzk.........",
      "..kuzk..........",
      "..kdk...........",
      "..kk............",
      "................",
      "................",
    ],
  },
  "permanent-pen": {
    size: 16,
    rows: [
      "................",
      "............kk..",
      "...........krrk.",
      "..........krrk..",
      ".........kwhk...",
      "........kRrk....",
      ".......kRrk.....",
      "......kRrk......",
      ".....kRrk.......",
      "....kRrk........",
      "...khsk.........",
      "..khsk..........",
      "..kdk...........",
      "..kk............",
      "................",
      "................",
    ],
  },
  section: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      ".e..............",
      ".eGe............",
      ".eGGe...........",
      ".eGGGe.kkkkkkkk.",
      ".eGGe...........",
      ".eGe............",
      ".e..............",
      ".......gggggggg.",
      "................",
      ".......gggggg...",
      "................",
      ".......gggggggg.",
      "................",
    ],
  },
  table: {
    size: 16,
    rows: [
      "................",
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kBBBkBBBBkBBBk.",
      ".kBBBkBBBBkBBBk.",
      ".kkkkkkkkkkkkkk.",
      ".kwwwgwwwwgwwwk.",
      ".kwwwgwwwwgwwwk.",
      ".kggggggggggggk.",
      ".kwwwgwwwwgwwwk.",
      ".kwwwgwwwwgwwwk.",
      ".kggggggggggggk.",
      ".kwwwgwwwwgwwwk.",
      ".kwwwgwwwwgwwwk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  doclink: {
    size: 16,
    rows: [
      "................",
      "..kkkkkk........",
      "..kwwwwkk.......",
      "..kwwwwkhk......",
      "..kwgggkkkk.....",
      "..kwwwwwwwk.....",
      "..kwgggggwk.....",
      "..kwwwwwwwk.....",
      "..kwgggggwk.BB..",
      "..kwwwwwwwkB..B.",
      "..kwgggggBBB..B.",
      "..kwwwwwBwkBBB..",
      "..kkkkkkBkkB....",
      ".........BB.....",
      "................",
      "................",
    ],
  },
  dblink: {
    size: 16,
    rows: [
      "................",
      ".....kkkkk......",
      "...kkhhhhhkk....",
      "..khhhhhhhhhk...",
      "..kkkhhhhhkkk...",
      "..kwskkkkksgk...",
      "..kwssssssggk...",
      "..kwssssssggk...",
      "..kwssssssggBB..",
      "..kwssssssgBk.B.",
      "..kwsssssBBBk.B.",
      "...kksssBgkBBB..",
      ".....kkkBk.B....",
      ".........BB.....",
      "................",
      "................",
    ],
  },
  bolt: {
    size: 16,
    rows: [
      "................",
      ".......kkkkk....",
      "......kYYYvk....",
      ".....kYYYvk.....",
      "....kYYYvk......",
      "...kYYYYkkkk....",
      "..kYYYYYYYvk....",
      "..kkkkYYYvk.....",
      ".....kYYvk......",
      "....kYYvk.......",
      "....kYvk........",
      "...kYvk.........",
      "...kYk..........",
      "..kYk...........",
      "..kk............",
      "................",
    ],
  },
  "bolt-idle": {
    size: 16,
    rows: [
      "................",
      ".......ggggg....",
      "......gssssg....",
      ".....gssssg.....",
      "....gssssg......",
      "...gssssgggg....",
      "..gssssssssg....",
      "..ggggssssg.....",
      ".....gsssg......",
      "....gsssg.......",
      "....gssg........",
      "...gssg.........",
      "...gsg..........",
      "..gsg...........",
      "..gg............",
      "................",
    ],
  },
  key: {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "...kkk..........",
      "..kwYYk.........",
      ".kYYkYYkkkkkkkk.",
      ".kYk.kYYYYYYYvk.",
      ".kYYkYvkkkYkYkk.",
      "..kYYvk..kvkvk..",
      "...kkk...kkkkk..",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  "location-office": {
    size: 16,
    rows: [
      "................",
      "...kkkkkkk......",
      "...khhhhhk......",
      "...kBsBsBk......",
      "...ksssssk......",
      "...kBsBsBk......",
      "...kssssskkkkk..",
      "...kBsBsBkhhhk..",
      "...ksssssksBsk..",
      "...kBsBsBksssk..",
      "...ksssssksBsk..",
      "...kBsBsBksssk..",
      "...ksdddsksBsk..",
      "...ksdddsksssk..",
      "...kkkkkkkkkkk..",
      "................",
    ],
  },
  "location-home": {
    size: 16,
    rows: [
      "................",
      "................",
      "............zzz.",
      ".....kk....kkz..",
      "....kRRk.kk..z..",
      "...kRRRRk....z..",
      "..kRRRRRRk...z..",
      ".kkkkkkkkkk..z..",
      "..kwwwwwwk...z..",
      "..kBwwwwBk...z..",
      "..kwwzzwwk...z..",
      "..kwwzzwwk...z..",
      "..kwwzzwwk...z..",
      "..kkkkkkkk..kzk.",
      "................",
      "................",
    ],
  },
  "location-travel": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "......kkkk......",
      ".....kk..kk.....",
      ".kkkkkkkkkkkkkk.",
      ".kuuYuuuuuuYuuk.",
      ".kuzYzzzzzzYzzk.",
      ".kuzYzzzzzzYzzk.",
      ".kuzYzzzzzzYzzk.",
      ".kuzYzzzzzzYzzk.",
      ".kuzYzzzzzzYzzk.",
      ".kzzYzzzzzzYzzk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
  },
  "location-island": {
    size: 16,
    rows: [
      "................",
      ".....eeeeee.....",
      "...eeGGGGGGee...",
      "..eGGGeGGeGGGe..",
      ".eGGe.ezze.eGGe.",
      ".ee...zz....ee..",
      "......zz........",
      ".......zz.......",
      ".......zz.......",
      ".......zz.......",
      "....kkkzzkkk....",
      "..kkuuuuuuuukk..",
      ".kuuuuuuuuuuuuk.",
      ".aaaaaaaaaaaaaa.",
      ".BBBBBBBBBBBBBB.",
      "................",
    ],
  },
  "mail-new": {
    size: 16,
    rows: [
      "................",
      "........o..Y..o.",
      ".........oYYYo..",
      ".........YYYYY..",
      "........YYYoYYY.",
      ".........YYYYY..",
      ".kkkkkkkkoYYYo..",
      ".kdwwwwwowwYk.o.",
      ".kwdwwwwwwdwk...",
      ".kwwdwwwwdwwk...",
      ".kwwwdwwdwwwk...",
      ".kwwwwddwwwwk...",
      ".kwwwwwwwwwwk...",
      ".kggggggggggk...",
      ".kkkkkkkkkkkk...",
      "................",
    ],
  },
  lock: {
    size: 16,
    rows: [
      "................",
      ".....kkkkkk.....",
      "....khhhhhhk....",
      "...khskkkksgk...",
      "...khsk..ksgk...",
      "...khsk..ksgk...",
      "...khsk..ksgk...",
      ".kkkkkkkkkkkkkk.",
      ".kwYYYYYYYYYYvk.",
      ".kwYYYYkkYYYYvk.",
      ".kwYYYYkkYYYYvk.",
      ".kwYYYYkkYYYYvk.",
      ".kwYYYYYYYYYYvk.",
      ".kvvvvvvvvvvvvk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  server: {
    size: 16,
    rows: [
      "................",
      "....kkkkkkkk....",
      "....khssssgk....",
      "....khkkkkgk....",
      "....khssssgk....",
      "....khkkkkgk....",
      "....khssssgk....",
      "....khsssGgk....",
      "....khssssgk....",
      "....khgsgsgk....",
      "....khssssgk....",
      "....khgsgsgk....",
      "....khssssgk....",
      "....kggggggk....",
      "....kkkkkkkk....",
      "................",
    ],
  },
  pc: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".khhhhhhhhhhhgk.",
      ".khkkkkkkkkkkgk.",
      ".khkccttttttkgk.",
      ".khkctttttttkgk.",
      ".khkttttttttkgk.",
      ".khkttttttttkgk.",
      ".khkttttttttkgk.",
      ".khkttttttttkgk.",
      ".khkkkkkkkkkkgk.",
      ".kggggggggggggk.",
      ".kkkkkkkkkkkkkk.",
      ".....khssgk.....",
      "...kkkkkkkkkk...",
      "................",
    ],
  },
  info: {
    size: 16,
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkaaaBBBkk...",
      "..kaaBBwwBBBBk..",
      "..kaBBBwwBBBBk..",
      ".kaBBBBBBBBBBBk.",
      ".kaBBBwwwBBBBBk.",
      ".kBBBBBwwBBBBBk.",
      ".kBBBBBwwBBBBBk.",
      ".kBBBBBwwBBBBbk.",
      ".kBBBBBwwBBBBbk.",
      "..kBBBwwwwBBbk..",
      "..kBBBBBBBBbbk..",
      "...kkbbbbbbkk...",
      ".....kkkkkk.....",
      "................",
    ],
  },
  properties: {
    size: 16,
    rows: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".knnnnnnnnnnnnk.",
      ".kkkkkkkkkkkkkk.",
      ".khhhhhkssssssk.",
      ".khhhhhkkkkkkkk.",
      ".khhhhhhhhhhhhk.",
      ".khhbbhhggggghk.",
      ".khhhhhhhhhhhhk.",
      ".khbbbhhggggghk.",
      ".khhbbhhhhhhhhk.",
      ".khhbbhhggggghk.",
      ".khbbbbhhhhhhhk.",
      ".khhhhhhhhhhhhk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  question: {
    size: 16,
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkaaaBBBkk...",
      "..kaaBwwwwBBBk..",
      "..kaBwwBBwwBBk..",
      ".kaBBBBBBwwBBBk.",
      ".kaBBBBBwwBBBBk.",
      ".kBBBBBwwBBBBBk.",
      ".kBBBBBwwBBBBBk.",
      ".kBBBBBBBBBBBbk.",
      ".kBBBBBwwBBBBbk.",
      "..kBBBBwwBBBbk..",
      "..kBBBBBBBBbbk..",
      "...kkbbbbbbkk...",
      ".....kkkkkk.....",
      "................",
    ],
  },
  warning: {
    size: 16,
    rows: [
      "................",
      ".......kk.......",
      "......kYYk......",
      "......kYYk......",
      ".....kYYYYk.....",
      ".....kYkkYk.....",
      "....kYYkkYYk....",
      "....kYYkkYYk....",
      "...kYYYkkYYYk...",
      "...kYYYkkYYYk...",
      "..kYYYYYYYYYYk..",
      "..kYYYYkkYYYYk..",
      ".kYYYYYkkYYYYYk.",
      ".kvvvvvvvvvvvvk.",
      ".kkkkkkkkkkkkkk.",
      "................",
    ],
  },
  error: {
    size: 16,
    rows: [
      "................",
      ".....kkkkkk.....",
      "...kkiiiRRRkk...",
      "..kiiRRRRRRRRk..",
      "..kiwwRRRRwwRk..",
      ".kiRRwwRRwwRRRk.",
      ".kiRRRwwwwRRRRk.",
      ".kRRRRRwwRRRRRk.",
      ".kRRRRRwwRRRRRk.",
      ".kRRRRwwwwRRRrk.",
      ".kRRRwwRRwwRRrk.",
      "..kRwwRRRRwwrk..",
      "..kRRRRRRRRrrk..",
      "...kkrrrrrrkk...",
      ".....kkkkkk.....",
      "................",
    ],
  },
  chat: {
    size: 16,
    rows: [
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      ".kwwwwwwwwwwwwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwggggggggggwk.",
      ".kwwwwwwwwwwwwk.",
      ".kwggggggggwwwk.",
      ".kwwwwwwwwwwwwk.",
      "..kkkwkkkkkkkk..",
      "....kwk.........",
      "....kk..........",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  "close-x": {
    size: 16,
    rows: [
      "................",
      "................",
      "................",
      "...hh......hh...",
      "...hkk....kkh...",
      "....hkk..kkh....",
      ".....hkkkkh.....",
      "......hkkh......",
      ".....hkkkkh.....",
      "....hkkhhkkh....",
      "...hkkh..hkkh...",
      "...hhh....hhh...",
      "................",
      "................",
      "................",
      "................",
    ],
  },
};
